# spinclass's conformist overlay, merged with conformist.lib.presets.{eng,eng-go}
# in flake.nix (conformist.lib.evalModule). presets.eng enables the
# eng-convention linters (eng-versioning, flake-outputs/lock, the justfile-*
# roster); presets.eng-go carries the canonical goimports -> gofumpt chain.
# Here live the repo-specific formatters/linters (shfmt, shellcheck, statix,
# deadnix) and excludes. golangci-lint lives in ./conformist-impure.nix (it
# needs ambient `go` + a writable cache, unavailable in this sandboxed lane —
# see flake.nix's conformistImpureEval). tommy fmt (*.toml) and the
# tommy-codegen repair linter have no registry program and need the `tommy`
# flake input, so they are inlined in flake.nix instead (a standalone module
# file can't see flake inputs) — see conformistTommyModule there.
#
# Replaces the former hand-written ./conformist.toml (docs/features/0019).
{ pkgs, ... }:
{
  programs.nixfmt.enable = true;

  linters = {
    # Nix linters (no autofix wired — check-only, like shellcheck).
    statix.enable = true;
    deadnix.enable = true;

    # shellcheck (read-only linter, no autofix). Registry default includes
    # lack *.bats, which zz-tests_bats/ uses.
    shellcheck = {
      enable = true;
      includes = [
        "*.sh"
        "*.bash"
        "*.bats"
      ];
    };

    # eng-versioning(7): go.mod's module path derives the key already
    # (code.linenisgreat.com/spinclass -> SPINCLASS_VERSION), pinned
    # explicitly to document the version.env contract (matches
    # maneater/nebulous).
    eng-versioning.key = "SPINCLASS_VERSION";
  };

  settings = {
    # shfmt: a raw stanza rather than `programs.shfmt.enable` — the module
    # cannot emit `-ci` via an option and its default includes lack `*.bats`,
    # both required by this repo's shell style: 2-space indent, simplify,
    # case-branch indent, over *.sh / *.bash / *.bats (matches the old
    # [formatter.shfmt] stanza exactly).
    formatter.shfmt = {
      command = "${pkgs.shfmt}/bin/shfmt";
      options = [
        "-w"
        "-i"
        "2"
        "-s"
        "-ci"
      ];
      includes = [
        "*.sh"
        "*.bash"
        "*.bats"
      ];
    };

    # Generated / locked / prose / hand-formatted — not formatted or linted.
    excludes = [
      "flake.lock"
      "go.sum"
      "gomod2nix.toml"
      "sweatfile"
      "LICENSE"
      "*.md"
      "result"
      "result-*"
      ".tmp/**"
      # Generated by tommy; regenerate via `just gen-tommy`, never hand-format.
      "internal/sweatfile/sweatfile_tommy.go"
      # roff manpage sources are hand-maintained; no formatter owns them.
      "cmd/spinclass/doc/*"
    ];
  };
}
