// Code generated by tommy 0.4.6 (41efed3); DO NOT EDIT.

package sweatfile

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type sweatfileStartCommandsHandle struct {
	node *cst.Node
}
type sweatfileMCPsHandle struct {
	node *cst.Node
}
type sweatfilePreMergeSkillsHandle struct {
	node *cst.Node
}
type sweatfileRemotesHandle struct {
	node *cst.Node
}
type SweatfileDocument struct {
	data           Sweatfile
	cstDoc         *document.Document
	model          *cst.Value
	startCommands  []sweatfileStartCommandsHandle
	mCPs           []sweatfileMCPsHandle
	preMergeSkills []sweatfilePreMergeSkillsHandle
	remotes        []sweatfileRemotesHandle
}

func DecodeSweatfile(input []byte) (*SweatfileDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &SweatfileDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vClaude, _ok := model.Get("claude"); _ok && _vClaude.Kind == cst.VTable {
		_vClaude.MarkSeen()
		claudeVal0 := &Claude{}
		if _vClaudeAllow, _ok := _vClaude.Get("allow"); _ok && _vClaudeAllow.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vClaudeAllow.Leaf); _xok {
				claudeVal0.Allow = _x
				if claudeVal0.Allow == nil {
					claudeVal0.Allow = []string{}
				}
				_vClaudeAllow.MarkConsumed()
			}
		}
		d.data.Claude = claudeVal0
	} else {
		claudeVal0 := &Claude{}
		_foundClaude := false
		if _vAllow, _ok := model.Get("allow"); _ok && _vAllow.Kind == cst.VLeaf {
			_foundClaude = true
			if _x, _xok := cst.ExtractStringSlice(_vAllow.Leaf); _xok {
				claudeVal0.Allow = _x
				if claudeVal0.Allow == nil {
					claudeVal0.Allow = []string{}
				}
				_vAllow.MarkConsumed()
			}
		}
		if _foundClaude {
			d.data.Claude = claudeVal0
		}
	}
	if _vGit, _ok := model.Get("git"); _ok && _vGit.Kind == cst.VTable {
		_vGit.MarkSeen()
		gitVal1 := &Git{}
		if _vGitExcludes, _ok := _vGit.Get("excludes"); _ok && _vGitExcludes.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vGitExcludes.Leaf); _xok {
				gitVal1.Excludes = _x
				if gitVal1.Excludes == nil {
					gitVal1.Excludes = []string{}
				}
				_vGitExcludes.MarkConsumed()
			}
		}
		d.data.Git = gitVal1
	} else {
		gitVal1 := &Git{}
		_foundGit := false
		if _vExcludes, _ok := model.Get("excludes"); _ok && _vExcludes.Kind == cst.VLeaf {
			_foundGit = true
			if _x, _xok := cst.ExtractStringSlice(_vExcludes.Leaf); _xok {
				gitVal1.Excludes = _x
				if gitVal1.Excludes == nil {
					gitVal1.Excludes = []string{}
				}
				_vExcludes.MarkConsumed()
			}
		}
		if _foundGit {
			d.data.Git = gitVal1
		}
	}
	if _vDirenv, _ok := model.Get("direnv"); _ok && _vDirenv.Kind == cst.VTable {
		_vDirenv.MarkSeen()
		direnvVal2 := &Direnv{}
		if _vDirenvEnvrc, _ok := _vDirenv.Get("envrc"); _ok && _vDirenvEnvrc.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vDirenvEnvrc.Leaf); _xok {
				direnvVal2.Envrc = _x
				if direnvVal2.Envrc == nil {
					direnvVal2.Envrc = []string{}
				}
				_vDirenvEnvrc.MarkConsumed()
			}
		}
		if _vDirenvDotenv, _ok := _vDirenv.Get("dotenv"); _ok && _vDirenvDotenv.Kind == cst.VTable {
			_vDirenvDotenv.MarkSeen()
			direnvVal2.Dotenv = make(map[string]string)
			for _iDirenvDotenv := range _vDirenvDotenv.Fields {
				_fDirenvDotenv := &_vDirenvDotenv.Fields[_iDirenvDotenv]
				if _fDirenvDotenv.Val.Kind == cst.VLeaf {
					if _s, _sok := cst.ExtractString(_fDirenvDotenv.Val.Leaf); _sok {
						direnvVal2.Dotenv[_fDirenvDotenv.Key] = _s
						_fDirenvDotenv.Val.MarkConsumed()
					}
				}
			}
		}
		d.data.Direnv = direnvVal2
	} else {
		direnvVal2 := &Direnv{}
		_foundDirenv := false
		if _vEnvrc, _ok := model.Get("envrc"); _ok && _vEnvrc.Kind == cst.VLeaf {
			_foundDirenv = true
			if _x, _xok := cst.ExtractStringSlice(_vEnvrc.Leaf); _xok {
				direnvVal2.Envrc = _x
				if direnvVal2.Envrc == nil {
					direnvVal2.Envrc = []string{}
				}
				_vEnvrc.MarkConsumed()
			}
		}
		if _foundDirenv {
			d.data.Direnv = direnvVal2
		}
	}
	if _vHooks, _ok := model.Get("hooks"); _ok && _vHooks.Kind == cst.VTable {
		_vHooks.MarkSeen()
		hooksVal3 := &Hooks{}
		if _vHooksCreate, _ok := _vHooks.Get("create"); _ok && _vHooksCreate.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksCreate.Leaf); _xok {
				hooksVal3.Create = &_x
				_vHooksCreate.MarkConsumed()
			}
		}
		if _vHooksStop, _ok := _vHooks.Get("stop"); _ok && _vHooksStop.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksStop.Leaf); _xok {
				hooksVal3.Stop = &_x
				_vHooksStop.MarkConsumed()
			}
		}
		if _vHooksPreMerge, _ok := _vHooks.Get("pre-merge"); _ok && _vHooksPreMerge.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksPreMerge.Leaf); _xok {
				hooksVal3.PreMerge = &_x
				_vHooksPreMerge.MarkConsumed()
			}
		}
		if _vHooksRepair, _ok := _vHooks.Get("repair"); _ok && _vHooksRepair.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksRepair.Leaf); _xok {
				hooksVal3.Repair = &_x
				_vHooksRepair.MarkConsumed()
			}
		}
		if _vHooksPreCommit, _ok := _vHooks.Get("pre-commit"); _ok && _vHooksPreCommit.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksPreCommit.Leaf); _xok {
				hooksVal3.PreCommit = &_x
				_vHooksPreCommit.MarkConsumed()
			}
		}
		if _vHooksOnAttach, _ok := _vHooks.Get("on-attach"); _ok && _vHooksOnAttach.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksOnAttach.Leaf); _xok {
				hooksVal3.OnAttach = &_x
				_vHooksOnAttach.MarkConsumed()
			}
		}
		if _vHooksOnDetach, _ok := _vHooks.Get("on-detach"); _ok && _vHooksOnDetach.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksOnDetach.Leaf); _xok {
				hooksVal3.OnDetach = &_x
				_vHooksOnDetach.MarkConsumed()
			}
		}
		if _vHooksDisallowMainWorktree, _ok := _vHooks.Get("disallow-main-worktree"); _ok && _vHooksDisallowMainWorktree.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisallowMainWorktree.Leaf); _xok {
				hooksVal3.DisallowMainWorktree = &_x
				_vHooksDisallowMainWorktree.MarkConsumed()
			}
		}
		if _vHooksToolUseLog, _ok := _vHooks.Get("tool-use-log"); _ok && _vHooksToolUseLog.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksToolUseLog.Leaf); _xok {
				hooksVal3.ToolUseLog = &_x
				_vHooksToolUseLog.MarkConsumed()
			}
		}
		if _vHooksDisableMerge, _ok := _vHooks.Get("disable-merge"); _ok && _vHooksDisableMerge.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableMerge.Leaf); _xok {
				hooksVal3.DisableMerge = &_x
				_vHooksDisableMerge.MarkConsumed()
			}
		}
		if _vHooksDisableRepair, _ok := _vHooks.Get("disable-repair"); _ok && _vHooksDisableRepair.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableRepair.Leaf); _xok {
				hooksVal3.DisableRepair = &_x
				_vHooksDisableRepair.MarkConsumed()
			}
		}
		if _vHooksDisablePreCommit, _ok := _vHooks.Get("disable-pre-commit"); _ok && _vHooksDisablePreCommit.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisablePreCommit.Leaf); _xok {
				hooksVal3.DisablePreCommit = &_x
				_vHooksDisablePreCommit.MarkConsumed()
			}
		}
		if _vHooksDisableNixGc, _ok := _vHooks.Get("disable-nix-gc"); _ok && _vHooksDisableNixGc.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableNixGc.Leaf); _xok {
				hooksVal3.DisableNixGC = &_x
				_vHooksDisableNixGc.MarkConsumed()
			}
		}
		if _vHooksDisableImplicitSessions, _ok := _vHooks.Get("disable-implicit-sessions"); _ok && _vHooksDisableImplicitSessions.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableImplicitSessions.Leaf); _xok {
				hooksVal3.DisableImplicitSessions = &_x
				_vHooksDisableImplicitSessions.MarkConsumed()
			}
		}
		if _vHooksDisableMergeBuildWorktree, _ok := _vHooks.Get("disable-merge-build-worktree"); _ok && _vHooksDisableMergeBuildWorktree.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableMergeBuildWorktree.Leaf); _xok {
				hooksVal3.DisableMergeBuildWorktree = &_x
				_vHooksDisableMergeBuildWorktree.MarkConsumed()
			}
		}
		if _vHooksDisableWorktreePathRewrite, _ok := _vHooks.Get("disable-worktree-path-rewrite"); _ok && _vHooksDisableWorktreePathRewrite.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableWorktreePathRewrite.Leaf); _xok {
				hooksVal3.DisableWorktreePathRewrite = &_x
				_vHooksDisableWorktreePathRewrite.MarkConsumed()
			}
		}
		if _vHooksPreMergeOutputFormat, _ok := _vHooks.Get("pre-merge-output-format"); _ok && _vHooksPreMergeOutputFormat.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksPreMergeOutputFormat.Leaf); _xok {
				hooksVal3.PreMergeOutputFormat = &_x
				_vHooksPreMergeOutputFormat.MarkConsumed()
			}
		}
		if _vHooksInactivityTimeout, _ok := _vHooks.Get("inactivity-timeout"); _ok && _vHooksInactivityTimeout.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksInactivityTimeout.Leaf); _xok {
				hooksVal3.InactivityTimeout = &_x
				_vHooksInactivityTimeout.MarkConsumed()
			}
		}
		if _vHooksAutoRebuildOnResume, _ok := _vHooks.Get("auto-rebuild-on-resume"); _ok && _vHooksAutoRebuildOnResume.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksAutoRebuildOnResume.Leaf); _xok {
				hooksVal3.AutoRebuildOnResume = &_x
				_vHooksAutoRebuildOnResume.MarkConsumed()
			}
		}
		d.data.Hooks = hooksVal3
	} else {
		hooksVal3 := &Hooks{}
		_foundHooks := false
		if _vCreate, _ok := model.Get("create"); _ok && _vCreate.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vCreate.Leaf); _xok {
				hooksVal3.Create = &_x
				_vCreate.MarkConsumed()
			}
		}
		if _vStop, _ok := model.Get("stop"); _ok && _vStop.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vStop.Leaf); _xok {
				hooksVal3.Stop = &_x
				_vStop.MarkConsumed()
			}
		}
		if _vPreMerge, _ok := model.Get("pre-merge"); _ok && _vPreMerge.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vPreMerge.Leaf); _xok {
				hooksVal3.PreMerge = &_x
				_vPreMerge.MarkConsumed()
			}
		}
		if _vRepair, _ok := model.Get("repair"); _ok && _vRepair.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vRepair.Leaf); _xok {
				hooksVal3.Repair = &_x
				_vRepair.MarkConsumed()
			}
		}
		if _vPreCommit, _ok := model.Get("pre-commit"); _ok && _vPreCommit.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vPreCommit.Leaf); _xok {
				hooksVal3.PreCommit = &_x
				_vPreCommit.MarkConsumed()
			}
		}
		if _vOnAttach, _ok := model.Get("on-attach"); _ok && _vOnAttach.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vOnAttach.Leaf); _xok {
				hooksVal3.OnAttach = &_x
				_vOnAttach.MarkConsumed()
			}
		}
		if _vOnDetach, _ok := model.Get("on-detach"); _ok && _vOnDetach.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vOnDetach.Leaf); _xok {
				hooksVal3.OnDetach = &_x
				_vOnDetach.MarkConsumed()
			}
		}
		if _vDisallowMainWorktree, _ok := model.Get("disallow-main-worktree"); _ok && _vDisallowMainWorktree.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisallowMainWorktree.Leaf); _xok {
				hooksVal3.DisallowMainWorktree = &_x
				_vDisallowMainWorktree.MarkConsumed()
			}
		}
		if _vToolUseLog, _ok := model.Get("tool-use-log"); _ok && _vToolUseLog.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vToolUseLog.Leaf); _xok {
				hooksVal3.ToolUseLog = &_x
				_vToolUseLog.MarkConsumed()
			}
		}
		if _vDisableMerge, _ok := model.Get("disable-merge"); _ok && _vDisableMerge.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableMerge.Leaf); _xok {
				hooksVal3.DisableMerge = &_x
				_vDisableMerge.MarkConsumed()
			}
		}
		if _vDisableRepair, _ok := model.Get("disable-repair"); _ok && _vDisableRepair.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableRepair.Leaf); _xok {
				hooksVal3.DisableRepair = &_x
				_vDisableRepair.MarkConsumed()
			}
		}
		if _vDisablePreCommit, _ok := model.Get("disable-pre-commit"); _ok && _vDisablePreCommit.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisablePreCommit.Leaf); _xok {
				hooksVal3.DisablePreCommit = &_x
				_vDisablePreCommit.MarkConsumed()
			}
		}
		if _vDisableNixGc, _ok := model.Get("disable-nix-gc"); _ok && _vDisableNixGc.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableNixGc.Leaf); _xok {
				hooksVal3.DisableNixGC = &_x
				_vDisableNixGc.MarkConsumed()
			}
		}
		if _vDisableImplicitSessions, _ok := model.Get("disable-implicit-sessions"); _ok && _vDisableImplicitSessions.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableImplicitSessions.Leaf); _xok {
				hooksVal3.DisableImplicitSessions = &_x
				_vDisableImplicitSessions.MarkConsumed()
			}
		}
		if _vDisableMergeBuildWorktree, _ok := model.Get("disable-merge-build-worktree"); _ok && _vDisableMergeBuildWorktree.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableMergeBuildWorktree.Leaf); _xok {
				hooksVal3.DisableMergeBuildWorktree = &_x
				_vDisableMergeBuildWorktree.MarkConsumed()
			}
		}
		if _vDisableWorktreePathRewrite, _ok := model.Get("disable-worktree-path-rewrite"); _ok && _vDisableWorktreePathRewrite.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableWorktreePathRewrite.Leaf); _xok {
				hooksVal3.DisableWorktreePathRewrite = &_x
				_vDisableWorktreePathRewrite.MarkConsumed()
			}
		}
		if _vPreMergeOutputFormat, _ok := model.Get("pre-merge-output-format"); _ok && _vPreMergeOutputFormat.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vPreMergeOutputFormat.Leaf); _xok {
				hooksVal3.PreMergeOutputFormat = &_x
				_vPreMergeOutputFormat.MarkConsumed()
			}
		}
		if _vInactivityTimeout, _ok := model.Get("inactivity-timeout"); _ok && _vInactivityTimeout.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vInactivityTimeout.Leaf); _xok {
				hooksVal3.InactivityTimeout = &_x
				_vInactivityTimeout.MarkConsumed()
			}
		}
		if _vAutoRebuildOnResume, _ok := model.Get("auto-rebuild-on-resume"); _ok && _vAutoRebuildOnResume.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vAutoRebuildOnResume.Leaf); _xok {
				hooksVal3.AutoRebuildOnResume = &_x
				_vAutoRebuildOnResume.MarkConsumed()
			}
		}
		if _foundHooks {
			d.data.Hooks = hooksVal3
		}
	}
	if _vSysprompt, _ok := model.Get("sysprompt"); _ok && _vSysprompt.Kind == cst.VTable {
		_vSysprompt.MarkSeen()
		syspromptVal4 := &Sysprompt{}
		if _vSyspromptDocIndexDirs, _ok := _vSysprompt.Get("doc-index-dirs"); _ok && _vSyspromptDocIndexDirs.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSyspromptDocIndexDirs.Leaf); _xok {
				syspromptVal4.DocIndexDirs = _x
				if syspromptVal4.DocIndexDirs == nil {
					syspromptVal4.DocIndexDirs = []string{}
				}
				_vSyspromptDocIndexDirs.MarkConsumed()
			}
		}
		d.data.Sysprompt = syspromptVal4
	} else {
		syspromptVal4 := &Sysprompt{}
		_foundSysprompt := false
		if _vDocIndexDirs, _ok := model.Get("doc-index-dirs"); _ok && _vDocIndexDirs.Kind == cst.VLeaf {
			_foundSysprompt = true
			if _x, _xok := cst.ExtractStringSlice(_vDocIndexDirs.Leaf); _xok {
				syspromptVal4.DocIndexDirs = _x
				if syspromptVal4.DocIndexDirs == nil {
					syspromptVal4.DocIndexDirs = []string{}
				}
				_vDocIndexDirs.MarkConsumed()
			}
		}
		if _foundSysprompt {
			d.data.Sysprompt = syspromptVal4
		}
	}
	if _vSessionEntry, _ok := model.Get("session-entry"); _ok && _vSessionEntry.Kind == cst.VTable {
		_vSessionEntry.MarkSeen()
		sessionEntryVal5 := &SessionEntry{}
		if _vSessionEntryStart, _ok := _vSessionEntry.Get("start"); _ok && _vSessionEntryStart.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntryStart.Leaf); _xok {
				sessionEntryVal5.Start = _x
				if sessionEntryVal5.Start == nil {
					sessionEntryVal5.Start = []string{}
				}
				_vSessionEntryStart.MarkConsumed()
			}
		}
		if _vSessionEntryResume, _ok := _vSessionEntry.Get("resume"); _ok && _vSessionEntryResume.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntryResume.Leaf); _xok {
				sessionEntryVal5.Resume = _x
				if sessionEntryVal5.Resume == nil {
					sessionEntryVal5.Resume = []string{}
				}
				_vSessionEntryResume.MarkConsumed()
			}
		}
		if _vSessionEntryEnv, _ok := _vSessionEntry.Get("env"); _ok && _vSessionEntryEnv.Kind == cst.VTable {
			_vSessionEntryEnv.MarkSeen()
			sessionEntryVal5.Env = make(map[string]string)
			for _iSessionEntryEnv := range _vSessionEntryEnv.Fields {
				_fSessionEntryEnv := &_vSessionEntryEnv.Fields[_iSessionEntryEnv]
				if _fSessionEntryEnv.Val.Kind == cst.VLeaf {
					if _s, _sok := cst.ExtractString(_fSessionEntryEnv.Val.Leaf); _sok {
						sessionEntryVal5.Env[_fSessionEntryEnv.Key] = _s
						_fSessionEntryEnv.Val.MarkConsumed()
					}
				}
			}
		}
		if _vSessionEntryLivenessProbe, _ok := _vSessionEntry.Get("liveness-probe"); _ok && _vSessionEntryLivenessProbe.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntryLivenessProbe.Leaf); _xok {
				sessionEntryVal5.LivenessProbe = _x
				if sessionEntryVal5.LivenessProbe == nil {
					sessionEntryVal5.LivenessProbe = []string{}
				}
				_vSessionEntryLivenessProbe.MarkConsumed()
			}
		}
		if _vSessionEntryTombstoneRetention, _ok := _vSessionEntry.Get("tombstone-retention"); _ok && _vSessionEntryTombstoneRetention.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSessionEntryTombstoneRetention.Leaf); _xok {
				sessionEntryVal5.TombstoneRetention = _x
				_vSessionEntryTombstoneRetention.MarkConsumed()
			}
		}
		if _vSessionEntrySpawnEntry, _ok := _vSessionEntry.Get("spawn-entry"); _ok && _vSessionEntrySpawnEntry.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntrySpawnEntry.Leaf); _xok {
				sessionEntryVal5.SpawnEntry = _x
				if sessionEntryVal5.SpawnEntry == nil {
					sessionEntryVal5.SpawnEntry = []string{}
				}
				_vSessionEntrySpawnEntry.MarkConsumed()
			}
		}
		if _vSessionEntrySpawnWindow, _ok := _vSessionEntry.Get("spawn-window"); _ok && _vSessionEntrySpawnWindow.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntrySpawnWindow.Leaf); _xok {
				sessionEntryVal5.SpawnWindow = _x
				if sessionEntryVal5.SpawnWindow == nil {
					sessionEntryVal5.SpawnWindow = []string{}
				}
				_vSessionEntrySpawnWindow.MarkConsumed()
			}
		}
		d.data.SessionEntry = sessionEntryVal5
	} else {
		sessionEntryVal5 := &SessionEntry{}
		_foundSessionEntry := false
		if _vStart, _ok := model.Get("start"); _ok && _vStart.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vStart.Leaf); _xok {
				sessionEntryVal5.Start = _x
				if sessionEntryVal5.Start == nil {
					sessionEntryVal5.Start = []string{}
				}
				_vStart.MarkConsumed()
			}
		}
		if _vResume, _ok := model.Get("resume"); _ok && _vResume.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vResume.Leaf); _xok {
				sessionEntryVal5.Resume = _x
				if sessionEntryVal5.Resume == nil {
					sessionEntryVal5.Resume = []string{}
				}
				_vResume.MarkConsumed()
			}
		}
		if _vLivenessProbe, _ok := model.Get("liveness-probe"); _ok && _vLivenessProbe.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vLivenessProbe.Leaf); _xok {
				sessionEntryVal5.LivenessProbe = _x
				if sessionEntryVal5.LivenessProbe == nil {
					sessionEntryVal5.LivenessProbe = []string{}
				}
				_vLivenessProbe.MarkConsumed()
			}
		}
		if _vTombstoneRetention, _ok := model.Get("tombstone-retention"); _ok && _vTombstoneRetention.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractString(_vTombstoneRetention.Leaf); _xok {
				sessionEntryVal5.TombstoneRetention = _x
				_vTombstoneRetention.MarkConsumed()
			}
		}
		if _vSpawnEntry, _ok := model.Get("spawn-entry"); _ok && _vSpawnEntry.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vSpawnEntry.Leaf); _xok {
				sessionEntryVal5.SpawnEntry = _x
				if sessionEntryVal5.SpawnEntry == nil {
					sessionEntryVal5.SpawnEntry = []string{}
				}
				_vSpawnEntry.MarkConsumed()
			}
		}
		if _vSpawnWindow, _ok := model.Get("spawn-window"); _ok && _vSpawnWindow.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vSpawnWindow.Leaf); _xok {
				sessionEntryVal5.SpawnWindow = _x
				if sessionEntryVal5.SpawnWindow == nil {
					sessionEntryVal5.SpawnWindow = []string{}
				}
				_vSpawnWindow.MarkConsumed()
			}
		}
		if _foundSessionEntry {
			d.data.SessionEntry = sessionEntryVal5
		}
	}
	if _vStartCommands, _ok := model.Get("start-commands"); _ok && _vStartCommands.Kind == cst.VArray {
		_vStartCommands.MarkSeen()
		d.data.StartCommands = make([]StartCommand, len(_vStartCommands.Items))
		d.startCommands = make([]sweatfileStartCommandsHandle, len(_vStartCommands.Items))
		for i := range _vStartCommands.Items {
			_eStartCommands := &_vStartCommands.Items[i]
			_eStartCommands.MarkSeen()
			d.startCommands[i] = sweatfileStartCommandsHandle{node: _eStartCommands.Node}
			if _vStartCommandsName, _ok := _eStartCommands.Get("name"); _ok && _vStartCommandsName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsName.Leaf); _xok {
					d.data.StartCommands[i].Name = _x
					_vStartCommandsName.MarkConsumed()
				}
			}
			if _vStartCommandsDescription, _ok := _eStartCommands.Get("description"); _ok && _vStartCommandsDescription.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsDescription.Leaf); _xok {
					d.data.StartCommands[i].Description = _x
					_vStartCommandsDescription.MarkConsumed()
				}
			}
			if _vStartCommandsArgName, _ok := _eStartCommands.Get("arg-name"); _ok && _vStartCommandsArgName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsArgName.Leaf); _xok {
					d.data.StartCommands[i].ArgName = _x
					_vStartCommandsArgName.MarkConsumed()
				}
			}
			if _vStartCommandsArgHelp, _ok := _eStartCommands.Get("arg-help"); _ok && _vStartCommandsArgHelp.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsArgHelp.Leaf); _xok {
					d.data.StartCommands[i].ArgHelp = _x
					_vStartCommandsArgHelp.MarkConsumed()
				}
			}
			if _vStartCommandsArgRegex, _ok := _eStartCommands.Get("arg-regex"); _ok && _vStartCommandsArgRegex.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsArgRegex.Leaf); _xok {
					d.data.StartCommands[i].ArgRegex = &_x
					_vStartCommandsArgRegex.MarkConsumed()
				}
			}
			if _vStartCommandsExecCompletions, _ok := _eStartCommands.Get("exec-completions"); _ok && _vStartCommandsExecCompletions.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vStartCommandsExecCompletions.Leaf); _xok {
					d.data.StartCommands[i].ExecCompletions = _x
					if d.data.StartCommands[i].ExecCompletions == nil {
						d.data.StartCommands[i].ExecCompletions = []string{}
					}
					_vStartCommandsExecCompletions.MarkConsumed()
				}
			}
			if _vStartCommandsExecStart, _ok := _eStartCommands.Get("exec-start"); _ok && _vStartCommandsExecStart.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vStartCommandsExecStart.Leaf); _xok {
					d.data.StartCommands[i].ExecStart = _x
					if d.data.StartCommands[i].ExecStart == nil {
						d.data.StartCommands[i].ExecStart = []string{}
					}
					_vStartCommandsExecStart.MarkConsumed()
				}
			}
		}
	}
	if _eaStartCommands, _eaok := model.Get("start-commands"); _eaok && _eaStartCommands.IsEmptyArray() {
		_eaStartCommands.MarkConsumed()
		d.data.StartCommands = []StartCommand{}
	}
	if _vAllowedMcps, _ok := model.Get("allowed-mcps"); _ok && _vAllowedMcps.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vAllowedMcps.Leaf); _xok {
			d.data.AllowedMCPs = _x
			if d.data.AllowedMCPs == nil {
				d.data.AllowedMCPs = []string{}
			}
			_vAllowedMcps.MarkConsumed()
		}
	}
	if _vMcps, _ok := model.Get("mcps"); _ok && _vMcps.Kind == cst.VArray {
		_vMcps.MarkSeen()
		d.data.MCPs = make([]MCPServerDef, len(_vMcps.Items))
		d.mCPs = make([]sweatfileMCPsHandle, len(_vMcps.Items))
		for i := range _vMcps.Items {
			_eMcps := &_vMcps.Items[i]
			_eMcps.MarkSeen()
			d.mCPs[i] = sweatfileMCPsHandle{node: _eMcps.Node}
			if _vMcpsName, _ok := _eMcps.Get("name"); _ok && _vMcpsName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vMcpsName.Leaf); _xok {
					d.data.MCPs[i].Name = _x
					_vMcpsName.MarkConsumed()
				}
			}
			if _vMcpsCommand, _ok := _eMcps.Get("command"); _ok && _vMcpsCommand.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vMcpsCommand.Leaf); _xok {
					d.data.MCPs[i].Command = _x
					_vMcpsCommand.MarkConsumed()
				}
			}
			if _vMcpsArgs, _ok := _eMcps.Get("args"); _ok && _vMcpsArgs.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vMcpsArgs.Leaf); _xok {
					d.data.MCPs[i].Args = _x
					if d.data.MCPs[i].Args == nil {
						d.data.MCPs[i].Args = []string{}
					}
					_vMcpsArgs.MarkConsumed()
				}
			}
			if _vMcpsEnv, _ok := _eMcps.Get("env"); _ok && _vMcpsEnv.Kind == cst.VTable {
				_vMcpsEnv.MarkSeen()
				d.data.MCPs[i].Env = make(map[string]string)
				for _iMcpsEnv := range _vMcpsEnv.Fields {
					_fMcpsEnv := &_vMcpsEnv.Fields[_iMcpsEnv]
					if _fMcpsEnv.Val.Kind == cst.VLeaf {
						if _s, _sok := cst.ExtractString(_fMcpsEnv.Val.Leaf); _sok {
							d.data.MCPs[i].Env[_fMcpsEnv.Key] = _s
							_fMcpsEnv.Val.MarkConsumed()
						}
					}
				}
			}
		}
	}
	if _eaMcps, _eaok := model.Get("mcps"); _eaok && _eaMcps.IsEmptyArray() {
		_eaMcps.MarkConsumed()
		d.data.MCPs = []MCPServerDef{}
	}
	if _vPreMergeSkills, _ok := model.Get("pre-merge-skills"); _ok && _vPreMergeSkills.Kind == cst.VArray {
		_vPreMergeSkills.MarkSeen()
		d.data.PreMergeSkills = make([]PreMergeSkill, len(_vPreMergeSkills.Items))
		d.preMergeSkills = make([]sweatfilePreMergeSkillsHandle, len(_vPreMergeSkills.Items))
		for i := range _vPreMergeSkills.Items {
			_ePreMergeSkills := &_vPreMergeSkills.Items[i]
			_ePreMergeSkills.MarkSeen()
			d.preMergeSkills[i] = sweatfilePreMergeSkillsHandle{node: _ePreMergeSkills.Node}
			if _vPreMergeSkillsName, _ok := _ePreMergeSkills.Get("name"); _ok && _vPreMergeSkillsName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vPreMergeSkillsName.Leaf); _xok {
					d.data.PreMergeSkills[i].Name = _x
					_vPreMergeSkillsName.MarkConsumed()
				}
			}
			if _vPreMergeSkillsRationale, _ok := _ePreMergeSkills.Get("rationale"); _ok && _vPreMergeSkillsRationale.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vPreMergeSkillsRationale.Leaf); _xok {
					d.data.PreMergeSkills[i].Rationale = _x
					_vPreMergeSkillsRationale.MarkConsumed()
				}
			}
		}
	}
	if _eaPreMergeSkills, _eaok := model.Get("pre-merge-skills"); _eaok && _eaPreMergeSkills.IsEmptyArray() {
		_eaPreMergeSkills.MarkConsumed()
		d.data.PreMergeSkills = []PreMergeSkill{}
	}
	if _vRemotes, _ok := model.Get("remotes"); _ok && _vRemotes.Kind == cst.VArray {
		_vRemotes.MarkSeen()
		d.data.Remotes = make([]Remote, len(_vRemotes.Items))
		d.remotes = make([]sweatfileRemotesHandle, len(_vRemotes.Items))
		for i := range _vRemotes.Items {
			_eRemotes := &_vRemotes.Items[i]
			_eRemotes.MarkSeen()
			d.remotes[i] = sweatfileRemotesHandle{node: _eRemotes.Node}
			if _vRemotesName, _ok := _eRemotes.Get("name"); _ok && _vRemotesName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vRemotesName.Leaf); _xok {
					d.data.Remotes[i].Name = _x
					_vRemotesName.MarkConsumed()
				}
			}
			if _vRemotesSsh, _ok := _eRemotes.Get("ssh"); _ok && _vRemotesSsh.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vRemotesSsh.Leaf); _xok {
					d.data.Remotes[i].SSH = _x
					_vRemotesSsh.MarkConsumed()
				}
			}
			if _vRemotesAttach, _ok := _eRemotes.Get("attach"); _ok && _vRemotesAttach.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vRemotesAttach.Leaf); _xok {
					d.data.Remotes[i].Attach = _x
					if d.data.Remotes[i].Attach == nil {
						d.data.Remotes[i].Attach = []string{}
					}
					_vRemotesAttach.MarkConsumed()
				}
			}
			if _vRemotesRemove, _ok := _eRemotes.Get("remove"); _ok && _vRemotesRemove.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vRemotesRemove.Leaf); _xok {
					d.data.Remotes[i].Remove = _x
					_vRemotesRemove.MarkConsumed()
				}
			}
		}
	}
	if _eaRemotes, _eaok := model.Get("remotes"); _eaok && _eaRemotes.IsEmptyArray() {
		_eaRemotes.MarkConsumed()
		d.data.Remotes = []Remote{}
	}
	return d, nil
}

func (d *SweatfileDocument) Data() *Sweatfile {
	return &d.data
}

func (d *SweatfileDocument) Encode() ([]byte, error) {
	if d.data.Claude != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "claude")
		{
			if d.data.Claude.Allow != nil {
				if err := cst.SetAny(tableNode, "allow", d.data.Claude.Allow); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.Git != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "git")
		{
			if d.data.Git.Excludes != nil {
				if err := cst.SetAny(tableNode, "excludes", d.data.Git.Excludes); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.Direnv != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "direnv")
		{
			if d.data.Direnv.Envrc != nil {
				if err := cst.SetAny(tableNode, "envrc", d.data.Direnv.Envrc); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		if d.data.Direnv.Dotenv != nil {
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "dotenv")
			cst.DeleteAllValues(tableNode)
			for k, v := range d.data.Direnv.Dotenv {
				if err := cst.SetAny(tableNode, k, v); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.Hooks != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "hooks")
		if d.data.Hooks.Create != nil {
			if err := cst.SetAny(tableNode, "create", *d.data.Hooks.Create); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.Stop != nil {
			if err := cst.SetAny(tableNode, "stop", *d.data.Hooks.Stop); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.PreMerge != nil {
			if err := cst.SetAny(tableNode, "pre-merge", *d.data.Hooks.PreMerge); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.Repair != nil {
			if err := cst.SetAny(tableNode, "repair", *d.data.Hooks.Repair); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.PreCommit != nil {
			if err := cst.SetAny(tableNode, "pre-commit", *d.data.Hooks.PreCommit); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.OnAttach != nil {
			if err := cst.SetAny(tableNode, "on-attach", *d.data.Hooks.OnAttach); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.OnDetach != nil {
			if err := cst.SetAny(tableNode, "on-detach", *d.data.Hooks.OnDetach); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisallowMainWorktree != nil {
			if err := cst.SetAny(tableNode, "disallow-main-worktree", *d.data.Hooks.DisallowMainWorktree); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.ToolUseLog != nil {
			if err := cst.SetAny(tableNode, "tool-use-log", *d.data.Hooks.ToolUseLog); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisableMerge != nil {
			if err := cst.SetAny(tableNode, "disable-merge", *d.data.Hooks.DisableMerge); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisableRepair != nil {
			if err := cst.SetAny(tableNode, "disable-repair", *d.data.Hooks.DisableRepair); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisablePreCommit != nil {
			if err := cst.SetAny(tableNode, "disable-pre-commit", *d.data.Hooks.DisablePreCommit); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisableNixGC != nil {
			if err := cst.SetAny(tableNode, "disable-nix-gc", *d.data.Hooks.DisableNixGC); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisableImplicitSessions != nil {
			if err := cst.SetAny(tableNode, "disable-implicit-sessions", *d.data.Hooks.DisableImplicitSessions); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisableMergeBuildWorktree != nil {
			if err := cst.SetAny(tableNode, "disable-merge-build-worktree", *d.data.Hooks.DisableMergeBuildWorktree); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisableWorktreePathRewrite != nil {
			if err := cst.SetAny(tableNode, "disable-worktree-path-rewrite", *d.data.Hooks.DisableWorktreePathRewrite); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.PreMergeOutputFormat != nil {
			if err := cst.SetAny(tableNode, "pre-merge-output-format", *d.data.Hooks.PreMergeOutputFormat); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.InactivityTimeout != nil {
			if err := cst.SetAny(tableNode, "inactivity-timeout", *d.data.Hooks.InactivityTimeout); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.AutoRebuildOnResume != nil {
			if err := cst.SetAny(tableNode, "auto-rebuild-on-resume", *d.data.Hooks.AutoRebuildOnResume); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Sysprompt != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "sysprompt")
		{
			if d.data.Sysprompt.DocIndexDirs != nil {
				if err := cst.SetAny(tableNode, "doc-index-dirs", d.data.Sysprompt.DocIndexDirs); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.SessionEntry != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "session-entry")
		{
			if d.data.SessionEntry.Start != nil {
				if err := cst.SetAny(tableNode, "start", d.data.SessionEntry.Start); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		{
			if d.data.SessionEntry.Resume != nil {
				if err := cst.SetAny(tableNode, "resume", d.data.SessionEntry.Resume); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		if d.data.SessionEntry.Env != nil {
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "env")
			cst.DeleteAllValues(tableNode)
			for k, v := range d.data.SessionEntry.Env {
				if err := cst.SetAny(tableNode, k, v); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		{
			if d.data.SessionEntry.LivenessProbe != nil {
				if err := cst.SetAny(tableNode, "liveness-probe", d.data.SessionEntry.LivenessProbe); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		if d.data.SessionEntry.TombstoneRetention != "" || cst.HasValue(tableNode, "tombstone-retention") {
			if err := cst.SetAny(tableNode, "tombstone-retention", d.data.SessionEntry.TombstoneRetention); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		{
			if d.data.SessionEntry.SpawnEntry != nil {
				if err := cst.SetAny(tableNode, "spawn-entry", d.data.SessionEntry.SpawnEntry); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		{
			if d.data.SessionEntry.SpawnWindow != nil {
				if err := cst.SetAny(tableNode, "spawn-window", d.data.SessionEntry.SpawnWindow); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	{
		for i := range d.data.StartCommands {
			var container *cst.Node
			if i < len(d.startCommands) {
				container = d.startCommands[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "start-commands")
			}
			if d.data.StartCommands[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.StartCommands[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.StartCommands[i].Description != "" || cst.HasValue(container, "description") {
				if err := cst.SetAny(container, "description", d.data.StartCommands[i].Description); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.StartCommands[i].ArgName != "" || cst.HasValue(container, "arg-name") {
				if err := cst.SetAny(container, "arg-name", d.data.StartCommands[i].ArgName); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.StartCommands[i].ArgHelp != "" || cst.HasValue(container, "arg-help") {
				if err := cst.SetAny(container, "arg-help", d.data.StartCommands[i].ArgHelp); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.StartCommands[i].ArgRegex != nil {
				if err := cst.SetAny(container, "arg-regex", *d.data.StartCommands[i].ArgRegex); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				if d.data.StartCommands[i].ExecCompletions != nil {
					if err := cst.SetAny(container, "exec-completions", d.data.StartCommands[i].ExecCompletions); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			{
				if d.data.StartCommands[i].ExecStart != nil {
					if err := cst.SetAny(container, "exec-start", d.data.StartCommands[i].ExecStart); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
		}
	}
	{
		if d.data.AllowedMCPs != nil {
			if err := cst.SetAny(d.cstDoc.Root(), "allowed-mcps", d.data.AllowedMCPs); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		for i := range d.data.MCPs {
			var container *cst.Node
			if i < len(d.mCPs) {
				container = d.mCPs[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "mcps")
			}
			if d.data.MCPs[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.MCPs[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.MCPs[i].Command != "" || cst.HasValue(container, "command") {
				if err := cst.SetAny(container, "command", d.data.MCPs[i].Command); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				if d.data.MCPs[i].Args != nil {
					if err := cst.SetAny(container, "args", d.data.MCPs[i].Args); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.MCPs[i].Env != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), container, "env")
				cst.DeleteAllValues(tableNode)
				for k, v := range d.data.MCPs[i].Env {
					if err := cst.SetAny(tableNode, k, v); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
		}
	}
	{
		for i := range d.data.PreMergeSkills {
			var container *cst.Node
			if i < len(d.preMergeSkills) {
				container = d.preMergeSkills[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "pre-merge-skills")
			}
			if d.data.PreMergeSkills[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.PreMergeSkills[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.PreMergeSkills[i].Rationale != "" || cst.HasValue(container, "rationale") {
				if err := cst.SetAny(container, "rationale", d.data.PreMergeSkills[i].Rationale); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	{
		for i := range d.data.Remotes {
			var container *cst.Node
			if i < len(d.remotes) {
				container = d.remotes[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "remotes")
			}
			if d.data.Remotes[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.Remotes[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Remotes[i].SSH != "" || cst.HasValue(container, "ssh") {
				if err := cst.SetAny(container, "ssh", d.data.Remotes[i].SSH); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				if d.data.Remotes[i].Attach != nil {
					if err := cst.SetAny(container, "attach", d.data.Remotes[i].Attach); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Remotes[i].Remove != false || cst.HasValue(container, "remove") {
				if err := cst.SetAny(container, "remove", d.data.Remotes[i].Remove); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *SweatfileDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *SweatfileDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *SweatfileDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *SweatfileDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *SweatfileDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeSweatfileInto(data *Sweatfile, sub *cst.Value) error {
	if _vClaude, _ok := sub.Get("claude"); _ok && _vClaude.Kind == cst.VTable {
		_vClaude.MarkSeen()
		claudeVal0 := &Claude{}
		if _vClaudeAllow, _ok := _vClaude.Get("allow"); _ok && _vClaudeAllow.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vClaudeAllow.Leaf); _xok {
				claudeVal0.Allow = _x
				if claudeVal0.Allow == nil {
					claudeVal0.Allow = []string{}
				}
				_vClaudeAllow.MarkConsumed()
			}
		}
		data.Claude = claudeVal0
	} else {
		claudeVal0 := &Claude{}
		_foundClaude := false
		if _vAllow, _ok := sub.Get("allow"); _ok && _vAllow.Kind == cst.VLeaf {
			_foundClaude = true
			if _x, _xok := cst.ExtractStringSlice(_vAllow.Leaf); _xok {
				claudeVal0.Allow = _x
				if claudeVal0.Allow == nil {
					claudeVal0.Allow = []string{}
				}
				_vAllow.MarkConsumed()
			}
		}
		if _foundClaude {
			data.Claude = claudeVal0
		}
	}
	if _vGit, _ok := sub.Get("git"); _ok && _vGit.Kind == cst.VTable {
		_vGit.MarkSeen()
		gitVal1 := &Git{}
		if _vGitExcludes, _ok := _vGit.Get("excludes"); _ok && _vGitExcludes.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vGitExcludes.Leaf); _xok {
				gitVal1.Excludes = _x
				if gitVal1.Excludes == nil {
					gitVal1.Excludes = []string{}
				}
				_vGitExcludes.MarkConsumed()
			}
		}
		data.Git = gitVal1
	} else {
		gitVal1 := &Git{}
		_foundGit := false
		if _vExcludes, _ok := sub.Get("excludes"); _ok && _vExcludes.Kind == cst.VLeaf {
			_foundGit = true
			if _x, _xok := cst.ExtractStringSlice(_vExcludes.Leaf); _xok {
				gitVal1.Excludes = _x
				if gitVal1.Excludes == nil {
					gitVal1.Excludes = []string{}
				}
				_vExcludes.MarkConsumed()
			}
		}
		if _foundGit {
			data.Git = gitVal1
		}
	}
	if _vDirenv, _ok := sub.Get("direnv"); _ok && _vDirenv.Kind == cst.VTable {
		_vDirenv.MarkSeen()
		direnvVal2 := &Direnv{}
		if _vDirenvEnvrc, _ok := _vDirenv.Get("envrc"); _ok && _vDirenvEnvrc.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vDirenvEnvrc.Leaf); _xok {
				direnvVal2.Envrc = _x
				if direnvVal2.Envrc == nil {
					direnvVal2.Envrc = []string{}
				}
				_vDirenvEnvrc.MarkConsumed()
			}
		}
		if _vDirenvDotenv, _ok := _vDirenv.Get("dotenv"); _ok && _vDirenvDotenv.Kind == cst.VTable {
			_vDirenvDotenv.MarkSeen()
			direnvVal2.Dotenv = make(map[string]string)
			for _iDirenvDotenv := range _vDirenvDotenv.Fields {
				_fDirenvDotenv := &_vDirenvDotenv.Fields[_iDirenvDotenv]
				if _fDirenvDotenv.Val.Kind == cst.VLeaf {
					if _s, _sok := cst.ExtractString(_fDirenvDotenv.Val.Leaf); _sok {
						direnvVal2.Dotenv[_fDirenvDotenv.Key] = _s
						_fDirenvDotenv.Val.MarkConsumed()
					}
				}
			}
		}
		data.Direnv = direnvVal2
	} else {
		direnvVal2 := &Direnv{}
		_foundDirenv := false
		if _vEnvrc, _ok := sub.Get("envrc"); _ok && _vEnvrc.Kind == cst.VLeaf {
			_foundDirenv = true
			if _x, _xok := cst.ExtractStringSlice(_vEnvrc.Leaf); _xok {
				direnvVal2.Envrc = _x
				if direnvVal2.Envrc == nil {
					direnvVal2.Envrc = []string{}
				}
				_vEnvrc.MarkConsumed()
			}
		}
		if _foundDirenv {
			data.Direnv = direnvVal2
		}
	}
	if _vHooks, _ok := sub.Get("hooks"); _ok && _vHooks.Kind == cst.VTable {
		_vHooks.MarkSeen()
		hooksVal3 := &Hooks{}
		if _vHooksCreate, _ok := _vHooks.Get("create"); _ok && _vHooksCreate.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksCreate.Leaf); _xok {
				hooksVal3.Create = &_x
				_vHooksCreate.MarkConsumed()
			}
		}
		if _vHooksStop, _ok := _vHooks.Get("stop"); _ok && _vHooksStop.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksStop.Leaf); _xok {
				hooksVal3.Stop = &_x
				_vHooksStop.MarkConsumed()
			}
		}
		if _vHooksPreMerge, _ok := _vHooks.Get("pre-merge"); _ok && _vHooksPreMerge.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksPreMerge.Leaf); _xok {
				hooksVal3.PreMerge = &_x
				_vHooksPreMerge.MarkConsumed()
			}
		}
		if _vHooksRepair, _ok := _vHooks.Get("repair"); _ok && _vHooksRepair.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksRepair.Leaf); _xok {
				hooksVal3.Repair = &_x
				_vHooksRepair.MarkConsumed()
			}
		}
		if _vHooksPreCommit, _ok := _vHooks.Get("pre-commit"); _ok && _vHooksPreCommit.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksPreCommit.Leaf); _xok {
				hooksVal3.PreCommit = &_x
				_vHooksPreCommit.MarkConsumed()
			}
		}
		if _vHooksOnAttach, _ok := _vHooks.Get("on-attach"); _ok && _vHooksOnAttach.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksOnAttach.Leaf); _xok {
				hooksVal3.OnAttach = &_x
				_vHooksOnAttach.MarkConsumed()
			}
		}
		if _vHooksOnDetach, _ok := _vHooks.Get("on-detach"); _ok && _vHooksOnDetach.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksOnDetach.Leaf); _xok {
				hooksVal3.OnDetach = &_x
				_vHooksOnDetach.MarkConsumed()
			}
		}
		if _vHooksDisallowMainWorktree, _ok := _vHooks.Get("disallow-main-worktree"); _ok && _vHooksDisallowMainWorktree.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisallowMainWorktree.Leaf); _xok {
				hooksVal3.DisallowMainWorktree = &_x
				_vHooksDisallowMainWorktree.MarkConsumed()
			}
		}
		if _vHooksToolUseLog, _ok := _vHooks.Get("tool-use-log"); _ok && _vHooksToolUseLog.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksToolUseLog.Leaf); _xok {
				hooksVal3.ToolUseLog = &_x
				_vHooksToolUseLog.MarkConsumed()
			}
		}
		if _vHooksDisableMerge, _ok := _vHooks.Get("disable-merge"); _ok && _vHooksDisableMerge.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableMerge.Leaf); _xok {
				hooksVal3.DisableMerge = &_x
				_vHooksDisableMerge.MarkConsumed()
			}
		}
		if _vHooksDisableRepair, _ok := _vHooks.Get("disable-repair"); _ok && _vHooksDisableRepair.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableRepair.Leaf); _xok {
				hooksVal3.DisableRepair = &_x
				_vHooksDisableRepair.MarkConsumed()
			}
		}
		if _vHooksDisablePreCommit, _ok := _vHooks.Get("disable-pre-commit"); _ok && _vHooksDisablePreCommit.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisablePreCommit.Leaf); _xok {
				hooksVal3.DisablePreCommit = &_x
				_vHooksDisablePreCommit.MarkConsumed()
			}
		}
		if _vHooksDisableNixGc, _ok := _vHooks.Get("disable-nix-gc"); _ok && _vHooksDisableNixGc.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableNixGc.Leaf); _xok {
				hooksVal3.DisableNixGC = &_x
				_vHooksDisableNixGc.MarkConsumed()
			}
		}
		if _vHooksDisableImplicitSessions, _ok := _vHooks.Get("disable-implicit-sessions"); _ok && _vHooksDisableImplicitSessions.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableImplicitSessions.Leaf); _xok {
				hooksVal3.DisableImplicitSessions = &_x
				_vHooksDisableImplicitSessions.MarkConsumed()
			}
		}
		if _vHooksDisableMergeBuildWorktree, _ok := _vHooks.Get("disable-merge-build-worktree"); _ok && _vHooksDisableMergeBuildWorktree.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableMergeBuildWorktree.Leaf); _xok {
				hooksVal3.DisableMergeBuildWorktree = &_x
				_vHooksDisableMergeBuildWorktree.MarkConsumed()
			}
		}
		if _vHooksDisableWorktreePathRewrite, _ok := _vHooks.Get("disable-worktree-path-rewrite"); _ok && _vHooksDisableWorktreePathRewrite.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksDisableWorktreePathRewrite.Leaf); _xok {
				hooksVal3.DisableWorktreePathRewrite = &_x
				_vHooksDisableWorktreePathRewrite.MarkConsumed()
			}
		}
		if _vHooksPreMergeOutputFormat, _ok := _vHooks.Get("pre-merge-output-format"); _ok && _vHooksPreMergeOutputFormat.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksPreMergeOutputFormat.Leaf); _xok {
				hooksVal3.PreMergeOutputFormat = &_x
				_vHooksPreMergeOutputFormat.MarkConsumed()
			}
		}
		if _vHooksInactivityTimeout, _ok := _vHooks.Get("inactivity-timeout"); _ok && _vHooksInactivityTimeout.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHooksInactivityTimeout.Leaf); _xok {
				hooksVal3.InactivityTimeout = &_x
				_vHooksInactivityTimeout.MarkConsumed()
			}
		}
		if _vHooksAutoRebuildOnResume, _ok := _vHooks.Get("auto-rebuild-on-resume"); _ok && _vHooksAutoRebuildOnResume.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vHooksAutoRebuildOnResume.Leaf); _xok {
				hooksVal3.AutoRebuildOnResume = &_x
				_vHooksAutoRebuildOnResume.MarkConsumed()
			}
		}
		data.Hooks = hooksVal3
	} else {
		hooksVal3 := &Hooks{}
		_foundHooks := false
		if _vCreate, _ok := sub.Get("create"); _ok && _vCreate.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vCreate.Leaf); _xok {
				hooksVal3.Create = &_x
				_vCreate.MarkConsumed()
			}
		}
		if _vStop, _ok := sub.Get("stop"); _ok && _vStop.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vStop.Leaf); _xok {
				hooksVal3.Stop = &_x
				_vStop.MarkConsumed()
			}
		}
		if _vPreMerge, _ok := sub.Get("pre-merge"); _ok && _vPreMerge.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vPreMerge.Leaf); _xok {
				hooksVal3.PreMerge = &_x
				_vPreMerge.MarkConsumed()
			}
		}
		if _vRepair, _ok := sub.Get("repair"); _ok && _vRepair.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vRepair.Leaf); _xok {
				hooksVal3.Repair = &_x
				_vRepair.MarkConsumed()
			}
		}
		if _vPreCommit, _ok := sub.Get("pre-commit"); _ok && _vPreCommit.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vPreCommit.Leaf); _xok {
				hooksVal3.PreCommit = &_x
				_vPreCommit.MarkConsumed()
			}
		}
		if _vOnAttach, _ok := sub.Get("on-attach"); _ok && _vOnAttach.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vOnAttach.Leaf); _xok {
				hooksVal3.OnAttach = &_x
				_vOnAttach.MarkConsumed()
			}
		}
		if _vOnDetach, _ok := sub.Get("on-detach"); _ok && _vOnDetach.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vOnDetach.Leaf); _xok {
				hooksVal3.OnDetach = &_x
				_vOnDetach.MarkConsumed()
			}
		}
		if _vDisallowMainWorktree, _ok := sub.Get("disallow-main-worktree"); _ok && _vDisallowMainWorktree.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisallowMainWorktree.Leaf); _xok {
				hooksVal3.DisallowMainWorktree = &_x
				_vDisallowMainWorktree.MarkConsumed()
			}
		}
		if _vToolUseLog, _ok := sub.Get("tool-use-log"); _ok && _vToolUseLog.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vToolUseLog.Leaf); _xok {
				hooksVal3.ToolUseLog = &_x
				_vToolUseLog.MarkConsumed()
			}
		}
		if _vDisableMerge, _ok := sub.Get("disable-merge"); _ok && _vDisableMerge.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableMerge.Leaf); _xok {
				hooksVal3.DisableMerge = &_x
				_vDisableMerge.MarkConsumed()
			}
		}
		if _vDisableRepair, _ok := sub.Get("disable-repair"); _ok && _vDisableRepair.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableRepair.Leaf); _xok {
				hooksVal3.DisableRepair = &_x
				_vDisableRepair.MarkConsumed()
			}
		}
		if _vDisablePreCommit, _ok := sub.Get("disable-pre-commit"); _ok && _vDisablePreCommit.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisablePreCommit.Leaf); _xok {
				hooksVal3.DisablePreCommit = &_x
				_vDisablePreCommit.MarkConsumed()
			}
		}
		if _vDisableNixGc, _ok := sub.Get("disable-nix-gc"); _ok && _vDisableNixGc.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableNixGc.Leaf); _xok {
				hooksVal3.DisableNixGC = &_x
				_vDisableNixGc.MarkConsumed()
			}
		}
		if _vDisableImplicitSessions, _ok := sub.Get("disable-implicit-sessions"); _ok && _vDisableImplicitSessions.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableImplicitSessions.Leaf); _xok {
				hooksVal3.DisableImplicitSessions = &_x
				_vDisableImplicitSessions.MarkConsumed()
			}
		}
		if _vDisableMergeBuildWorktree, _ok := sub.Get("disable-merge-build-worktree"); _ok && _vDisableMergeBuildWorktree.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableMergeBuildWorktree.Leaf); _xok {
				hooksVal3.DisableMergeBuildWorktree = &_x
				_vDisableMergeBuildWorktree.MarkConsumed()
			}
		}
		if _vDisableWorktreePathRewrite, _ok := sub.Get("disable-worktree-path-rewrite"); _ok && _vDisableWorktreePathRewrite.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vDisableWorktreePathRewrite.Leaf); _xok {
				hooksVal3.DisableWorktreePathRewrite = &_x
				_vDisableWorktreePathRewrite.MarkConsumed()
			}
		}
		if _vPreMergeOutputFormat, _ok := sub.Get("pre-merge-output-format"); _ok && _vPreMergeOutputFormat.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vPreMergeOutputFormat.Leaf); _xok {
				hooksVal3.PreMergeOutputFormat = &_x
				_vPreMergeOutputFormat.MarkConsumed()
			}
		}
		if _vInactivityTimeout, _ok := sub.Get("inactivity-timeout"); _ok && _vInactivityTimeout.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractString(_vInactivityTimeout.Leaf); _xok {
				hooksVal3.InactivityTimeout = &_x
				_vInactivityTimeout.MarkConsumed()
			}
		}
		if _vAutoRebuildOnResume, _ok := sub.Get("auto-rebuild-on-resume"); _ok && _vAutoRebuildOnResume.Kind == cst.VLeaf {
			_foundHooks = true
			if _x, _xok := cst.ExtractBool(_vAutoRebuildOnResume.Leaf); _xok {
				hooksVal3.AutoRebuildOnResume = &_x
				_vAutoRebuildOnResume.MarkConsumed()
			}
		}
		if _foundHooks {
			data.Hooks = hooksVal3
		}
	}
	if _vSysprompt, _ok := sub.Get("sysprompt"); _ok && _vSysprompt.Kind == cst.VTable {
		_vSysprompt.MarkSeen()
		syspromptVal4 := &Sysprompt{}
		if _vSyspromptDocIndexDirs, _ok := _vSysprompt.Get("doc-index-dirs"); _ok && _vSyspromptDocIndexDirs.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSyspromptDocIndexDirs.Leaf); _xok {
				syspromptVal4.DocIndexDirs = _x
				if syspromptVal4.DocIndexDirs == nil {
					syspromptVal4.DocIndexDirs = []string{}
				}
				_vSyspromptDocIndexDirs.MarkConsumed()
			}
		}
		data.Sysprompt = syspromptVal4
	} else {
		syspromptVal4 := &Sysprompt{}
		_foundSysprompt := false
		if _vDocIndexDirs, _ok := sub.Get("doc-index-dirs"); _ok && _vDocIndexDirs.Kind == cst.VLeaf {
			_foundSysprompt = true
			if _x, _xok := cst.ExtractStringSlice(_vDocIndexDirs.Leaf); _xok {
				syspromptVal4.DocIndexDirs = _x
				if syspromptVal4.DocIndexDirs == nil {
					syspromptVal4.DocIndexDirs = []string{}
				}
				_vDocIndexDirs.MarkConsumed()
			}
		}
		if _foundSysprompt {
			data.Sysprompt = syspromptVal4
		}
	}
	if _vSessionEntry, _ok := sub.Get("session-entry"); _ok && _vSessionEntry.Kind == cst.VTable {
		_vSessionEntry.MarkSeen()
		sessionEntryVal5 := &SessionEntry{}
		if _vSessionEntryStart, _ok := _vSessionEntry.Get("start"); _ok && _vSessionEntryStart.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntryStart.Leaf); _xok {
				sessionEntryVal5.Start = _x
				if sessionEntryVal5.Start == nil {
					sessionEntryVal5.Start = []string{}
				}
				_vSessionEntryStart.MarkConsumed()
			}
		}
		if _vSessionEntryResume, _ok := _vSessionEntry.Get("resume"); _ok && _vSessionEntryResume.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntryResume.Leaf); _xok {
				sessionEntryVal5.Resume = _x
				if sessionEntryVal5.Resume == nil {
					sessionEntryVal5.Resume = []string{}
				}
				_vSessionEntryResume.MarkConsumed()
			}
		}
		if _vSessionEntryEnv, _ok := _vSessionEntry.Get("env"); _ok && _vSessionEntryEnv.Kind == cst.VTable {
			_vSessionEntryEnv.MarkSeen()
			sessionEntryVal5.Env = make(map[string]string)
			for _iSessionEntryEnv := range _vSessionEntryEnv.Fields {
				_fSessionEntryEnv := &_vSessionEntryEnv.Fields[_iSessionEntryEnv]
				if _fSessionEntryEnv.Val.Kind == cst.VLeaf {
					if _s, _sok := cst.ExtractString(_fSessionEntryEnv.Val.Leaf); _sok {
						sessionEntryVal5.Env[_fSessionEntryEnv.Key] = _s
						_fSessionEntryEnv.Val.MarkConsumed()
					}
				}
			}
		}
		if _vSessionEntryLivenessProbe, _ok := _vSessionEntry.Get("liveness-probe"); _ok && _vSessionEntryLivenessProbe.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntryLivenessProbe.Leaf); _xok {
				sessionEntryVal5.LivenessProbe = _x
				if sessionEntryVal5.LivenessProbe == nil {
					sessionEntryVal5.LivenessProbe = []string{}
				}
				_vSessionEntryLivenessProbe.MarkConsumed()
			}
		}
		if _vSessionEntryTombstoneRetention, _ok := _vSessionEntry.Get("tombstone-retention"); _ok && _vSessionEntryTombstoneRetention.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSessionEntryTombstoneRetention.Leaf); _xok {
				sessionEntryVal5.TombstoneRetention = _x
				_vSessionEntryTombstoneRetention.MarkConsumed()
			}
		}
		if _vSessionEntrySpawnEntry, _ok := _vSessionEntry.Get("spawn-entry"); _ok && _vSessionEntrySpawnEntry.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntrySpawnEntry.Leaf); _xok {
				sessionEntryVal5.SpawnEntry = _x
				if sessionEntryVal5.SpawnEntry == nil {
					sessionEntryVal5.SpawnEntry = []string{}
				}
				_vSessionEntrySpawnEntry.MarkConsumed()
			}
		}
		if _vSessionEntrySpawnWindow, _ok := _vSessionEntry.Get("spawn-window"); _ok && _vSessionEntrySpawnWindow.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vSessionEntrySpawnWindow.Leaf); _xok {
				sessionEntryVal5.SpawnWindow = _x
				if sessionEntryVal5.SpawnWindow == nil {
					sessionEntryVal5.SpawnWindow = []string{}
				}
				_vSessionEntrySpawnWindow.MarkConsumed()
			}
		}
		data.SessionEntry = sessionEntryVal5
	} else {
		sessionEntryVal5 := &SessionEntry{}
		_foundSessionEntry := false
		if _vStart, _ok := sub.Get("start"); _ok && _vStart.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vStart.Leaf); _xok {
				sessionEntryVal5.Start = _x
				if sessionEntryVal5.Start == nil {
					sessionEntryVal5.Start = []string{}
				}
				_vStart.MarkConsumed()
			}
		}
		if _vResume, _ok := sub.Get("resume"); _ok && _vResume.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vResume.Leaf); _xok {
				sessionEntryVal5.Resume = _x
				if sessionEntryVal5.Resume == nil {
					sessionEntryVal5.Resume = []string{}
				}
				_vResume.MarkConsumed()
			}
		}
		if _vLivenessProbe, _ok := sub.Get("liveness-probe"); _ok && _vLivenessProbe.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vLivenessProbe.Leaf); _xok {
				sessionEntryVal5.LivenessProbe = _x
				if sessionEntryVal5.LivenessProbe == nil {
					sessionEntryVal5.LivenessProbe = []string{}
				}
				_vLivenessProbe.MarkConsumed()
			}
		}
		if _vTombstoneRetention, _ok := sub.Get("tombstone-retention"); _ok && _vTombstoneRetention.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractString(_vTombstoneRetention.Leaf); _xok {
				sessionEntryVal5.TombstoneRetention = _x
				_vTombstoneRetention.MarkConsumed()
			}
		}
		if _vSpawnEntry, _ok := sub.Get("spawn-entry"); _ok && _vSpawnEntry.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vSpawnEntry.Leaf); _xok {
				sessionEntryVal5.SpawnEntry = _x
				if sessionEntryVal5.SpawnEntry == nil {
					sessionEntryVal5.SpawnEntry = []string{}
				}
				_vSpawnEntry.MarkConsumed()
			}
		}
		if _vSpawnWindow, _ok := sub.Get("spawn-window"); _ok && _vSpawnWindow.Kind == cst.VLeaf {
			_foundSessionEntry = true
			if _x, _xok := cst.ExtractStringSlice(_vSpawnWindow.Leaf); _xok {
				sessionEntryVal5.SpawnWindow = _x
				if sessionEntryVal5.SpawnWindow == nil {
					sessionEntryVal5.SpawnWindow = []string{}
				}
				_vSpawnWindow.MarkConsumed()
			}
		}
		if _foundSessionEntry {
			data.SessionEntry = sessionEntryVal5
		}
	}
	if _vStartCommands, _ok := sub.Get("start-commands"); _ok && _vStartCommands.Kind == cst.VArray {
		_vStartCommands.MarkSeen()
		data.StartCommands = make([]StartCommand, len(_vStartCommands.Items))
		for i := range _vStartCommands.Items {
			_eStartCommands := &_vStartCommands.Items[i]
			_eStartCommands.MarkSeen()
			if _vStartCommandsName, _ok := _eStartCommands.Get("name"); _ok && _vStartCommandsName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsName.Leaf); _xok {
					data.StartCommands[i].Name = _x
					_vStartCommandsName.MarkConsumed()
				}
			}
			if _vStartCommandsDescription, _ok := _eStartCommands.Get("description"); _ok && _vStartCommandsDescription.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsDescription.Leaf); _xok {
					data.StartCommands[i].Description = _x
					_vStartCommandsDescription.MarkConsumed()
				}
			}
			if _vStartCommandsArgName, _ok := _eStartCommands.Get("arg-name"); _ok && _vStartCommandsArgName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsArgName.Leaf); _xok {
					data.StartCommands[i].ArgName = _x
					_vStartCommandsArgName.MarkConsumed()
				}
			}
			if _vStartCommandsArgHelp, _ok := _eStartCommands.Get("arg-help"); _ok && _vStartCommandsArgHelp.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsArgHelp.Leaf); _xok {
					data.StartCommands[i].ArgHelp = _x
					_vStartCommandsArgHelp.MarkConsumed()
				}
			}
			if _vStartCommandsArgRegex, _ok := _eStartCommands.Get("arg-regex"); _ok && _vStartCommandsArgRegex.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vStartCommandsArgRegex.Leaf); _xok {
					data.StartCommands[i].ArgRegex = &_x
					_vStartCommandsArgRegex.MarkConsumed()
				}
			}
			if _vStartCommandsExecCompletions, _ok := _eStartCommands.Get("exec-completions"); _ok && _vStartCommandsExecCompletions.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vStartCommandsExecCompletions.Leaf); _xok {
					data.StartCommands[i].ExecCompletions = _x
					if data.StartCommands[i].ExecCompletions == nil {
						data.StartCommands[i].ExecCompletions = []string{}
					}
					_vStartCommandsExecCompletions.MarkConsumed()
				}
			}
			if _vStartCommandsExecStart, _ok := _eStartCommands.Get("exec-start"); _ok && _vStartCommandsExecStart.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vStartCommandsExecStart.Leaf); _xok {
					data.StartCommands[i].ExecStart = _x
					if data.StartCommands[i].ExecStart == nil {
						data.StartCommands[i].ExecStart = []string{}
					}
					_vStartCommandsExecStart.MarkConsumed()
				}
			}
		}
	}
	if _eaStartCommands, _eaok := sub.Get("start-commands"); _eaok && _eaStartCommands.IsEmptyArray() {
		_eaStartCommands.MarkConsumed()
		data.StartCommands = []StartCommand{}
	}
	if _vAllowedMcps, _ok := sub.Get("allowed-mcps"); _ok && _vAllowedMcps.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vAllowedMcps.Leaf); _xok {
			data.AllowedMCPs = _x
			if data.AllowedMCPs == nil {
				data.AllowedMCPs = []string{}
			}
			_vAllowedMcps.MarkConsumed()
		}
	}
	if _vMcps, _ok := sub.Get("mcps"); _ok && _vMcps.Kind == cst.VArray {
		_vMcps.MarkSeen()
		data.MCPs = make([]MCPServerDef, len(_vMcps.Items))
		for i := range _vMcps.Items {
			_eMcps := &_vMcps.Items[i]
			_eMcps.MarkSeen()
			if _vMcpsName, _ok := _eMcps.Get("name"); _ok && _vMcpsName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vMcpsName.Leaf); _xok {
					data.MCPs[i].Name = _x
					_vMcpsName.MarkConsumed()
				}
			}
			if _vMcpsCommand, _ok := _eMcps.Get("command"); _ok && _vMcpsCommand.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vMcpsCommand.Leaf); _xok {
					data.MCPs[i].Command = _x
					_vMcpsCommand.MarkConsumed()
				}
			}
			if _vMcpsArgs, _ok := _eMcps.Get("args"); _ok && _vMcpsArgs.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vMcpsArgs.Leaf); _xok {
					data.MCPs[i].Args = _x
					if data.MCPs[i].Args == nil {
						data.MCPs[i].Args = []string{}
					}
					_vMcpsArgs.MarkConsumed()
				}
			}
			if _vMcpsEnv, _ok := _eMcps.Get("env"); _ok && _vMcpsEnv.Kind == cst.VTable {
				_vMcpsEnv.MarkSeen()
				data.MCPs[i].Env = make(map[string]string)
				for _iMcpsEnv := range _vMcpsEnv.Fields {
					_fMcpsEnv := &_vMcpsEnv.Fields[_iMcpsEnv]
					if _fMcpsEnv.Val.Kind == cst.VLeaf {
						if _s, _sok := cst.ExtractString(_fMcpsEnv.Val.Leaf); _sok {
							data.MCPs[i].Env[_fMcpsEnv.Key] = _s
							_fMcpsEnv.Val.MarkConsumed()
						}
					}
				}
			}
		}
	}
	if _eaMcps, _eaok := sub.Get("mcps"); _eaok && _eaMcps.IsEmptyArray() {
		_eaMcps.MarkConsumed()
		data.MCPs = []MCPServerDef{}
	}
	if _vPreMergeSkills, _ok := sub.Get("pre-merge-skills"); _ok && _vPreMergeSkills.Kind == cst.VArray {
		_vPreMergeSkills.MarkSeen()
		data.PreMergeSkills = make([]PreMergeSkill, len(_vPreMergeSkills.Items))
		for i := range _vPreMergeSkills.Items {
			_ePreMergeSkills := &_vPreMergeSkills.Items[i]
			_ePreMergeSkills.MarkSeen()
			if _vPreMergeSkillsName, _ok := _ePreMergeSkills.Get("name"); _ok && _vPreMergeSkillsName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vPreMergeSkillsName.Leaf); _xok {
					data.PreMergeSkills[i].Name = _x
					_vPreMergeSkillsName.MarkConsumed()
				}
			}
			if _vPreMergeSkillsRationale, _ok := _ePreMergeSkills.Get("rationale"); _ok && _vPreMergeSkillsRationale.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vPreMergeSkillsRationale.Leaf); _xok {
					data.PreMergeSkills[i].Rationale = _x
					_vPreMergeSkillsRationale.MarkConsumed()
				}
			}
		}
	}
	if _eaPreMergeSkills, _eaok := sub.Get("pre-merge-skills"); _eaok && _eaPreMergeSkills.IsEmptyArray() {
		_eaPreMergeSkills.MarkConsumed()
		data.PreMergeSkills = []PreMergeSkill{}
	}
	if _vRemotes, _ok := sub.Get("remotes"); _ok && _vRemotes.Kind == cst.VArray {
		_vRemotes.MarkSeen()
		data.Remotes = make([]Remote, len(_vRemotes.Items))
		for i := range _vRemotes.Items {
			_eRemotes := &_vRemotes.Items[i]
			_eRemotes.MarkSeen()
			if _vRemotesName, _ok := _eRemotes.Get("name"); _ok && _vRemotesName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vRemotesName.Leaf); _xok {
					data.Remotes[i].Name = _x
					_vRemotesName.MarkConsumed()
				}
			}
			if _vRemotesSsh, _ok := _eRemotes.Get("ssh"); _ok && _vRemotesSsh.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vRemotesSsh.Leaf); _xok {
					data.Remotes[i].SSH = _x
					_vRemotesSsh.MarkConsumed()
				}
			}
			if _vRemotesAttach, _ok := _eRemotes.Get("attach"); _ok && _vRemotesAttach.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vRemotesAttach.Leaf); _xok {
					data.Remotes[i].Attach = _x
					if data.Remotes[i].Attach == nil {
						data.Remotes[i].Attach = []string{}
					}
					_vRemotesAttach.MarkConsumed()
				}
			}
			if _vRemotesRemove, _ok := _eRemotes.Get("remove"); _ok && _vRemotesRemove.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vRemotesRemove.Leaf); _xok {
					data.Remotes[i].Remove = _x
					_vRemotesRemove.MarkConsumed()
				}
			}
		}
	}
	if _eaRemotes, _eaok := sub.Get("remotes"); _eaok && _eaRemotes.IsEmptyArray() {
		_eaRemotes.MarkConsumed()
		data.Remotes = []Remote{}
	}
	return nil
}

func EncodeSweatfileFrom(data *Sweatfile, doc *document.Document, container *cst.Node) error {
	if data.Claude != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "claude")
		{
			if data.Claude.Allow != nil {
				if err := cst.SetAny(tableNode, "allow", data.Claude.Allow); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.Git != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "git")
		{
			if data.Git.Excludes != nil {
				if err := cst.SetAny(tableNode, "excludes", data.Git.Excludes); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.Direnv != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "direnv")
		{
			if data.Direnv.Envrc != nil {
				if err := cst.SetAny(tableNode, "envrc", data.Direnv.Envrc); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		if data.Direnv.Dotenv != nil {
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "dotenv")
			cst.DeleteAllValues(tableNode)
			for k, v := range data.Direnv.Dotenv {
				if err := cst.SetAny(tableNode, k, v); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.Hooks != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "hooks")
		if data.Hooks.Create != nil {
			if err := cst.SetAny(tableNode, "create", *data.Hooks.Create); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.Stop != nil {
			if err := cst.SetAny(tableNode, "stop", *data.Hooks.Stop); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.PreMerge != nil {
			if err := cst.SetAny(tableNode, "pre-merge", *data.Hooks.PreMerge); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.Repair != nil {
			if err := cst.SetAny(tableNode, "repair", *data.Hooks.Repair); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.PreCommit != nil {
			if err := cst.SetAny(tableNode, "pre-commit", *data.Hooks.PreCommit); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.OnAttach != nil {
			if err := cst.SetAny(tableNode, "on-attach", *data.Hooks.OnAttach); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.OnDetach != nil {
			if err := cst.SetAny(tableNode, "on-detach", *data.Hooks.OnDetach); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisallowMainWorktree != nil {
			if err := cst.SetAny(tableNode, "disallow-main-worktree", *data.Hooks.DisallowMainWorktree); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.ToolUseLog != nil {
			if err := cst.SetAny(tableNode, "tool-use-log", *data.Hooks.ToolUseLog); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisableMerge != nil {
			if err := cst.SetAny(tableNode, "disable-merge", *data.Hooks.DisableMerge); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisableRepair != nil {
			if err := cst.SetAny(tableNode, "disable-repair", *data.Hooks.DisableRepair); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisablePreCommit != nil {
			if err := cst.SetAny(tableNode, "disable-pre-commit", *data.Hooks.DisablePreCommit); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisableNixGC != nil {
			if err := cst.SetAny(tableNode, "disable-nix-gc", *data.Hooks.DisableNixGC); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisableImplicitSessions != nil {
			if err := cst.SetAny(tableNode, "disable-implicit-sessions", *data.Hooks.DisableImplicitSessions); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisableMergeBuildWorktree != nil {
			if err := cst.SetAny(tableNode, "disable-merge-build-worktree", *data.Hooks.DisableMergeBuildWorktree); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisableWorktreePathRewrite != nil {
			if err := cst.SetAny(tableNode, "disable-worktree-path-rewrite", *data.Hooks.DisableWorktreePathRewrite); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.PreMergeOutputFormat != nil {
			if err := cst.SetAny(tableNode, "pre-merge-output-format", *data.Hooks.PreMergeOutputFormat); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.InactivityTimeout != nil {
			if err := cst.SetAny(tableNode, "inactivity-timeout", *data.Hooks.InactivityTimeout); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.AutoRebuildOnResume != nil {
			if err := cst.SetAny(tableNode, "auto-rebuild-on-resume", *data.Hooks.AutoRebuildOnResume); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Sysprompt != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "sysprompt")
		{
			if data.Sysprompt.DocIndexDirs != nil {
				if err := cst.SetAny(tableNode, "doc-index-dirs", data.Sysprompt.DocIndexDirs); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.SessionEntry != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "session-entry")
		{
			if data.SessionEntry.Start != nil {
				if err := cst.SetAny(tableNode, "start", data.SessionEntry.Start); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		{
			if data.SessionEntry.Resume != nil {
				if err := cst.SetAny(tableNode, "resume", data.SessionEntry.Resume); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		if data.SessionEntry.Env != nil {
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "env")
			cst.DeleteAllValues(tableNode)
			for k, v := range data.SessionEntry.Env {
				if err := cst.SetAny(tableNode, k, v); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		{
			if data.SessionEntry.LivenessProbe != nil {
				if err := cst.SetAny(tableNode, "liveness-probe", data.SessionEntry.LivenessProbe); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		if data.SessionEntry.TombstoneRetention != "" || cst.HasValue(tableNode, "tombstone-retention") {
			if err := cst.SetAny(tableNode, "tombstone-retention", data.SessionEntry.TombstoneRetention); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		{
			if data.SessionEntry.SpawnEntry != nil {
				if err := cst.SetAny(tableNode, "spawn-entry", data.SessionEntry.SpawnEntry); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		{
			if data.SessionEntry.SpawnWindow != nil {
				if err := cst.SetAny(tableNode, "spawn-window", data.SessionEntry.SpawnWindow); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	{
		_apStartCommands := container
		_existStartCommands := cst.FindChildArrayTableNodes(doc.Root(), _apStartCommands, "start-commands")
		for i := range data.StartCommands {
			var container *cst.Node
			if i < len(_existStartCommands) {
				container = _existStartCommands[i]
			} else {
				container = cst.AppendChildArrayTableEntry(doc.Root(), _apStartCommands, "start-commands")
			}
			if data.StartCommands[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.StartCommands[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.StartCommands[i].Description != "" || cst.HasValue(container, "description") {
				if err := cst.SetAny(container, "description", data.StartCommands[i].Description); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.StartCommands[i].ArgName != "" || cst.HasValue(container, "arg-name") {
				if err := cst.SetAny(container, "arg-name", data.StartCommands[i].ArgName); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.StartCommands[i].ArgHelp != "" || cst.HasValue(container, "arg-help") {
				if err := cst.SetAny(container, "arg-help", data.StartCommands[i].ArgHelp); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.StartCommands[i].ArgRegex != nil {
				if err := cst.SetAny(container, "arg-regex", *data.StartCommands[i].ArgRegex); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				if data.StartCommands[i].ExecCompletions != nil {
					if err := cst.SetAny(container, "exec-completions", data.StartCommands[i].ExecCompletions); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			{
				if data.StartCommands[i].ExecStart != nil {
					if err := cst.SetAny(container, "exec-start", data.StartCommands[i].ExecStart); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
		}
	}
	{
		if data.AllowedMCPs != nil {
			if err := cst.SetAny(container, "allowed-mcps", data.AllowedMCPs); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		_apMcps := container
		_existMcps := cst.FindChildArrayTableNodes(doc.Root(), _apMcps, "mcps")
		for i := range data.MCPs {
			var container *cst.Node
			if i < len(_existMcps) {
				container = _existMcps[i]
			} else {
				container = cst.AppendChildArrayTableEntry(doc.Root(), _apMcps, "mcps")
			}
			if data.MCPs[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.MCPs[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.MCPs[i].Command != "" || cst.HasValue(container, "command") {
				if err := cst.SetAny(container, "command", data.MCPs[i].Command); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				if data.MCPs[i].Args != nil {
					if err := cst.SetAny(container, "args", data.MCPs[i].Args); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.MCPs[i].Env != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), container, "env")
				cst.DeleteAllValues(tableNode)
				for k, v := range data.MCPs[i].Env {
					if err := cst.SetAny(tableNode, k, v); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
		}
	}
	{
		_apPreMergeSkills := container
		_existPreMergeSkills := cst.FindChildArrayTableNodes(doc.Root(), _apPreMergeSkills, "pre-merge-skills")
		for i := range data.PreMergeSkills {
			var container *cst.Node
			if i < len(_existPreMergeSkills) {
				container = _existPreMergeSkills[i]
			} else {
				container = cst.AppendChildArrayTableEntry(doc.Root(), _apPreMergeSkills, "pre-merge-skills")
			}
			if data.PreMergeSkills[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.PreMergeSkills[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.PreMergeSkills[i].Rationale != "" || cst.HasValue(container, "rationale") {
				if err := cst.SetAny(container, "rationale", data.PreMergeSkills[i].Rationale); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	{
		_apRemotes := container
		_existRemotes := cst.FindChildArrayTableNodes(doc.Root(), _apRemotes, "remotes")
		for i := range data.Remotes {
			var container *cst.Node
			if i < len(_existRemotes) {
				container = _existRemotes[i]
			} else {
				container = cst.AppendChildArrayTableEntry(doc.Root(), _apRemotes, "remotes")
			}
			if data.Remotes[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.Remotes[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Remotes[i].SSH != "" || cst.HasValue(container, "ssh") {
				if err := cst.SetAny(container, "ssh", data.Remotes[i].SSH); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				if data.Remotes[i].Attach != nil {
					if err := cst.SetAny(container, "attach", data.Remotes[i].Attach); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Remotes[i].Remove != false || cst.HasValue(container, "remove") {
				if err := cst.SetAny(container, "remove", data.Remotes[i].Remove); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	return nil
}
