// Code generated by tommy; DO NOT EDIT.

package sweatfile

import (
	"fmt"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
	"strings"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type startCommandHandle struct {
	node *cst.Node
}
type mCPServerDefHandle struct {
	node *cst.Node
}
type SweatfileDocument struct {
	data          Sweatfile
	cstDoc        *document.Document
	consumed      map[string]bool
	startCommands []startCommandHandle
	mCPs          []mCPServerDefHandle
}

func DecodeSweatfile(input []byte) (*SweatfileDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &SweatfileDocument{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "allowed-mcps":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				d.data.AllowedMCPs = v
				d.consumed["allowed-mcps"] = true
			}
		}
	}
	{
		var _ftClaude *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "claude" {
				_ftClaude = _ch
				break
			}
		}
		if _ftClaude != nil {
			d.consumed["claude"] = true
			claudeVal := &Claude{}
			for _, _kv := range _ftClaude.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "allow":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						claudeVal.Allow = v
						d.consumed["claude.allow"] = true
					}
				}
			}
			d.data.Claude = claudeVal
		} else {
			claudeVal := &Claude{}
			_found := false
			for _, _kv := range d.cstDoc.Root().Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "allow":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						claudeVal.Allow = v
						d.consumed["allow"] = true
					}
				}
			}
			if _found {
				d.data.Claude = claudeVal
			}
		}
	}
	{
		var _ftGit *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "git" {
				_ftGit = _ch
				break
			}
		}
		if _ftGit != nil {
			d.consumed["git"] = true
			gitVal := &Git{}
			for _, _kv := range _ftGit.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "excludes":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						gitVal.Excludes = v
						d.consumed["git.excludes"] = true
					}
				}
			}
			d.data.Git = gitVal
		} else {
			gitVal := &Git{}
			_found := false
			for _, _kv := range d.cstDoc.Root().Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "excludes":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						gitVal.Excludes = v
						d.consumed["excludes"] = true
					}
				}
			}
			if _found {
				d.data.Git = gitVal
			}
		}
	}
	{
		var _ftDirenv *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "direnv" {
				_ftDirenv = _ch
				break
			}
		}
		if _ftDirenv != nil {
			d.consumed["direnv"] = true
			direnvVal := &Direnv{}
			for _, _kv := range _ftDirenv.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "envrc":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						direnvVal.Envrc = v
						d.consumed["direnv.envrc"] = true
					}
				}
			}
			for _, _ch := range d.cstDoc.Root().Children {
				if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "direnv.dotenv" {
					direnvVal.Dotenv = cst.ExtractStringMap(_ch)
					d.consumed["direnv.dotenv"] = true
					for _ik := range direnvVal.Dotenv {
						d.consumed["direnv.dotenv"+"."+_ik] = true
					}
					break
				}
			}
			d.data.Direnv = direnvVal
		} else {
			direnvVal := &Direnv{}
			_found := false
			for _, _kv := range d.cstDoc.Root().Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "envrc":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						direnvVal.Envrc = v
						d.consumed["envrc"] = true
					}
				}
			}
			for _, _ch := range d.cstDoc.Root().Children {
				if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "dotenv" {
					direnvVal.Dotenv = cst.ExtractStringMap(_ch)
					_found = true
					d.consumed["dotenv"] = true
					for _ik := range direnvVal.Dotenv {
						d.consumed["dotenv"+"."+_ik] = true
					}
					break
				}
			}
			if _found {
				d.data.Direnv = direnvVal
			}
		}
	}
	{
		var _ftHooks *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "hooks" {
				_ftHooks = _ch
				break
			}
		}
		if _ftHooks != nil {
			d.consumed["hooks"] = true
			hooksVal := &Hooks{}
			for _, _kv := range _ftHooks.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "create":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.Create = &v
						d.consumed["hooks.create"] = true
					}
				case "stop":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.Stop = &v
						d.consumed["hooks.stop"] = true
					}
				case "pre-merge":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.PreMerge = &v
						d.consumed["hooks.pre-merge"] = true
					}
				case "on-attach":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.OnAttach = &v
						d.consumed["hooks.on-attach"] = true
					}
				case "on-detach":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.OnDetach = &v
						d.consumed["hooks.on-detach"] = true
					}
				case "disallow-main-worktree":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisallowMainWorktree = &v
						d.consumed["hooks.disallow-main-worktree"] = true
					}
				case "tool-use-log":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.ToolUseLog = &v
						d.consumed["hooks.tool-use-log"] = true
					}
				case "disable-merge":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisableMerge = &v
						d.consumed["hooks.disable-merge"] = true
					}
				case "disable-nix-gc":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisableNixGC = &v
						d.consumed["hooks.disable-nix-gc"] = true
					}
				}
			}
			d.data.Hooks = hooksVal
		} else {
			hooksVal := &Hooks{}
			_found := false
			for _, _kv := range d.cstDoc.Root().Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "create":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.Create = &v
						_found = true
						d.consumed["create"] = true
					}
				case "stop":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.Stop = &v
						_found = true
						d.consumed["stop"] = true
					}
				case "pre-merge":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.PreMerge = &v
						_found = true
						d.consumed["pre-merge"] = true
					}
				case "on-attach":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.OnAttach = &v
						_found = true
						d.consumed["on-attach"] = true
					}
				case "on-detach":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.OnDetach = &v
						_found = true
						d.consumed["on-detach"] = true
					}
				case "disallow-main-worktree":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisallowMainWorktree = &v
						_found = true
						d.consumed["disallow-main-worktree"] = true
					}
				case "tool-use-log":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.ToolUseLog = &v
						_found = true
						d.consumed["tool-use-log"] = true
					}
				case "disable-merge":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisableMerge = &v
						_found = true
						d.consumed["disable-merge"] = true
					}
				case "disable-nix-gc":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisableNixGC = &v
						_found = true
						d.consumed["disable-nix-gc"] = true
					}
				}
			}
			if _found {
				d.data.Hooks = hooksVal
			}
		}
	}
	{
		var _ftSessionEntry *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "session-entry" {
				_ftSessionEntry = _ch
				break
			}
		}
		if _ftSessionEntry != nil {
			d.consumed["session-entry"] = true
			sessionEntryVal := &SessionEntry{}
			for _, _kv := range _ftSessionEntry.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "start":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.Start = v
						d.consumed["session-entry.start"] = true
					}
				case "resume":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.Resume = v
						d.consumed["session-entry.resume"] = true
					}
				case "liveness-probe":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.LivenessProbe = v
						d.consumed["session-entry.liveness-probe"] = true
					}
				case "tombstone-retention":
					if v, ok := cst.ExtractString(_kv); ok {
						sessionEntryVal.TombstoneRetention = v
						d.consumed["session-entry.tombstone-retention"] = true
					}
				}
			}
			for _, _ch := range d.cstDoc.Root().Children {
				if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "session-entry.env" {
					sessionEntryVal.Env = cst.ExtractStringMap(_ch)
					d.consumed["session-entry.env"] = true
					for _ik := range sessionEntryVal.Env {
						d.consumed["session-entry.env"+"."+_ik] = true
					}
					break
				}
			}
			d.data.SessionEntry = sessionEntryVal
		} else {
			sessionEntryVal := &SessionEntry{}
			_found := false
			for _, _kv := range d.cstDoc.Root().Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "start":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.Start = v
						d.consumed["start"] = true
					}
				case "resume":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.Resume = v
						d.consumed["resume"] = true
					}
				case "liveness-probe":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.LivenessProbe = v
						d.consumed["liveness-probe"] = true
					}
				case "tombstone-retention":
					if v, ok := cst.ExtractString(_kv); ok {
						sessionEntryVal.TombstoneRetention = v
						_found = true
						d.consumed["tombstone-retention"] = true
					}
				}
			}
			for _, _ch := range d.cstDoc.Root().Children {
				if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "env" {
					sessionEntryVal.Env = cst.ExtractStringMap(_ch)
					_found = true
					d.consumed["env"] = true
					for _ik := range sessionEntryVal.Env {
						d.consumed["env"+"."+_ik] = true
					}
					break
				}
			}
			if _found {
				d.data.SessionEntry = sessionEntryVal
			}
		}
	}
	var _nodesStartCommands []*cst.Node
	for _, _ch := range d.cstDoc.Root().Children {
		if _ch.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_ch) == "start-commands" {
			_nodesStartCommands = append(_nodesStartCommands, _ch)
		}
	}
	d.startCommands = make([]startCommandHandle, len(_nodesStartCommands))
	d.data.StartCommands = make([]StartCommand, len(_nodesStartCommands))
	d.consumed["start-commands"] = true
	for i, _node := range _nodesStartCommands {
		d.startCommands[i] = startCommandHandle{node: _node}
		for _, _kv := range _node.Children {
			if _kv.Kind != cst.NodeKeyValue {
				continue
			}
			switch cst.KeyValueName(_kv) {
			case "name":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.StartCommands[i].Name = v
					d.consumed["start-commands.name"] = true
				}
			case "description":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.StartCommands[i].Description = v
					d.consumed["start-commands.description"] = true
				}
			case "arg-name":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.StartCommands[i].ArgName = v
					d.consumed["start-commands.arg-name"] = true
				}
			case "arg-help":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.StartCommands[i].ArgHelp = v
					d.consumed["start-commands.arg-help"] = true
				}
			case "arg-regex":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.StartCommands[i].ArgRegex = &v
					d.consumed["start-commands.arg-regex"] = true
				}
			case "exec-completions":
				if v, ok := cst.ExtractStringSlice(_kv); ok {
					d.data.StartCommands[i].ExecCompletions = v
					d.consumed["start-commands.exec-completions"] = true
				}
			case "exec-start":
				if v, ok := cst.ExtractStringSlice(_kv); ok {
					d.data.StartCommands[i].ExecStart = v
					d.consumed["start-commands.exec-start"] = true
				}
			}
		}
	}
	var _nodesMcps []*cst.Node
	for _, _ch := range d.cstDoc.Root().Children {
		if _ch.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_ch) == "mcps" {
			_nodesMcps = append(_nodesMcps, _ch)
		}
	}
	d.mCPs = make([]mCPServerDefHandle, len(_nodesMcps))
	d.data.MCPs = make([]MCPServerDef, len(_nodesMcps))
	d.consumed["mcps"] = true
	for i, _node := range _nodesMcps {
		d.mCPs[i] = mCPServerDefHandle{node: _node}
		for _, _kv := range _node.Children {
			if _kv.Kind != cst.NodeKeyValue {
				continue
			}
			switch cst.KeyValueName(_kv) {
			case "name":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.MCPs[i].Name = v
					d.consumed["mcps.name"] = true
				}
			case "command":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.MCPs[i].Command = v
					d.consumed["mcps.command"] = true
				}
			case "args":
				if v, ok := cst.ExtractStringSlice(_kv); ok {
					d.data.MCPs[i].Args = v
					d.consumed["mcps.args"] = true
				}
			}
		}
		{
			_pi := 0
			for _, _rc := range d.cstDoc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_rc) == "mcps" {
					if _pi > i {
						break
					}
					_pi++
					continue
				}
				if _pi == i+1 && _rc.Kind == cst.NodeTable && cst.TableHeaderKey(_rc) == "mcps.env" {
					d.data.MCPs[i].Env = cst.ExtractStringMap(_rc)
					d.consumed["mcps.env"] = true
					for _ik := range d.data.MCPs[i].Env {
						d.consumed["mcps.env"+"."+_ik] = true
					}
					break
				}
			}
		}
	}
	return d, nil
}
func (d *SweatfileDocument) Data() *Sweatfile {
	return &d.data
}
func (d *SweatfileDocument) Encode() ([]byte, error) {
	if d.data.Claude != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "claude")
		{
			if len(d.data.Claude.Allow) > 0 || cst.HasValue(tableNode, "allow") {
				if err := cst.SetAny(tableNode, "allow", d.data.Claude.Allow); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.Git != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "git")
		{
			if len(d.data.Git.Excludes) > 0 || cst.HasValue(tableNode, "excludes") {
				if err := cst.SetAny(tableNode, "excludes", d.data.Git.Excludes); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.Direnv != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "direnv")
		{
			if len(d.data.Direnv.Envrc) > 0 || cst.HasValue(tableNode, "envrc") {
				if err := cst.SetAny(tableNode, "envrc", d.data.Direnv.Envrc); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		if len(d.data.Direnv.Dotenv) > 0 {
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "dotenv")
			cst.DeleteAllValues(tableNode)
			for k, v := range d.data.Direnv.Dotenv {
				if err := cst.SetAny(tableNode, k, v); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.Hooks != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "hooks")
		if d.data.Hooks.Create != nil {
			if err := cst.SetAny(tableNode, "create", *d.data.Hooks.Create); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.Stop != nil {
			if err := cst.SetAny(tableNode, "stop", *d.data.Hooks.Stop); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.PreMerge != nil {
			if err := cst.SetAny(tableNode, "pre-merge", *d.data.Hooks.PreMerge); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.OnAttach != nil {
			if err := cst.SetAny(tableNode, "on-attach", *d.data.Hooks.OnAttach); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.OnDetach != nil {
			if err := cst.SetAny(tableNode, "on-detach", *d.data.Hooks.OnDetach); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisallowMainWorktree != nil {
			if err := cst.SetAny(tableNode, "disallow-main-worktree", *d.data.Hooks.DisallowMainWorktree); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.ToolUseLog != nil {
			if err := cst.SetAny(tableNode, "tool-use-log", *d.data.Hooks.ToolUseLog); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisableMerge != nil {
			if err := cst.SetAny(tableNode, "disable-merge", *d.data.Hooks.DisableMerge); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Hooks.DisableNixGC != nil {
			if err := cst.SetAny(tableNode, "disable-nix-gc", *d.data.Hooks.DisableNixGC); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.SessionEntry != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "session-entry")
		{
			if len(d.data.SessionEntry.Start) > 0 || cst.HasValue(tableNode, "start") {
				if err := cst.SetAny(tableNode, "start", d.data.SessionEntry.Start); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		{
			if len(d.data.SessionEntry.Resume) > 0 || cst.HasValue(tableNode, "resume") {
				if err := cst.SetAny(tableNode, "resume", d.data.SessionEntry.Resume); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		if len(d.data.SessionEntry.Env) > 0 {
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "env")
			cst.DeleteAllValues(tableNode)
			for k, v := range d.data.SessionEntry.Env {
				if err := cst.SetAny(tableNode, k, v); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		{
			if len(d.data.SessionEntry.LivenessProbe) > 0 || cst.HasValue(tableNode, "liveness-probe") {
				if err := cst.SetAny(tableNode, "liveness-probe", d.data.SessionEntry.LivenessProbe); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		if d.data.SessionEntry.TombstoneRetention != "" || cst.HasValue(tableNode, "tombstone-retention") {
			if err := cst.SetAny(tableNode, "tombstone-retention", d.data.SessionEntry.TombstoneRetention); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		for i := range d.data.StartCommands {
			var container *cst.Node
			if i < len(d.startCommands) {
				container = d.startCommands[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "start-commands")
			}
			if d.data.StartCommands[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.StartCommands[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.StartCommands[i].Description != "" || cst.HasValue(container, "description") {
				if err := cst.SetAny(container, "description", d.data.StartCommands[i].Description); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.StartCommands[i].ArgName != "" || cst.HasValue(container, "arg-name") {
				if err := cst.SetAny(container, "arg-name", d.data.StartCommands[i].ArgName); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.StartCommands[i].ArgHelp != "" || cst.HasValue(container, "arg-help") {
				if err := cst.SetAny(container, "arg-help", d.data.StartCommands[i].ArgHelp); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.StartCommands[i].ArgRegex != nil {
				if err := cst.SetAny(container, "arg-regex", *d.data.StartCommands[i].ArgRegex); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				if len(d.data.StartCommands[i].ExecCompletions) > 0 || cst.HasValue(container, "exec-completions") {
					if err := cst.SetAny(container, "exec-completions", d.data.StartCommands[i].ExecCompletions); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			{
				if len(d.data.StartCommands[i].ExecStart) > 0 || cst.HasValue(container, "exec-start") {
					if err := cst.SetAny(container, "exec-start", d.data.StartCommands[i].ExecStart); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
		}
	}
	{
		if len(d.data.AllowedMCPs) > 0 || cst.HasValue(d.cstDoc.Root(), "allowed-mcps") {
			if err := cst.SetAny(d.cstDoc.Root(), "allowed-mcps", d.data.AllowedMCPs); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		for i := range d.data.MCPs {
			var container *cst.Node
			if i < len(d.mCPs) {
				container = d.mCPs[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "mcps")
			}
			if d.data.MCPs[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.MCPs[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.MCPs[i].Command != "" || cst.HasValue(container, "command") {
				if err := cst.SetAny(container, "command", d.data.MCPs[i].Command); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				if len(d.data.MCPs[i].Args) > 0 || cst.HasValue(container, "args") {
					if err := cst.SetAny(container, "args", d.data.MCPs[i].Args); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if len(d.data.MCPs[i].Env) > 0 {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), container, "env")
				cst.DeleteAllValues(tableNode)
				for k, v := range d.data.MCPs[i].Env {
					if err := cst.SetAny(tableNode, k, v); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *SweatfileDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *SweatfileDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *SweatfileDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *SweatfileDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *SweatfileDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeSweatfileInto(data *Sweatfile, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "allowed-mcps":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				data.AllowedMCPs = v
				consumed[keyPrefix+"allowed-mcps"] = true
			}
		}
	}
	{
		var _ftClaude *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"claude" {
				_ftClaude = _ch
				break
			}
		}
		if _ftClaude != nil {
			consumed[keyPrefix+"claude"] = true
			claudeVal := &Claude{}
			for _, _kv := range _ftClaude.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "allow":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						claudeVal.Allow = v
						consumed[keyPrefix+"claude.allow"] = true
					}
				}
			}
			data.Claude = claudeVal
		} else {
			claudeVal := &Claude{}
			_found := false
			for _, _kv := range container.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "allow":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						claudeVal.Allow = v
						consumed["allow"] = true
					}
				}
			}
			if _found {
				data.Claude = claudeVal
			}
		}
	}
	{
		var _ftGit *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"git" {
				_ftGit = _ch
				break
			}
		}
		if _ftGit != nil {
			consumed[keyPrefix+"git"] = true
			gitVal := &Git{}
			for _, _kv := range _ftGit.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "excludes":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						gitVal.Excludes = v
						consumed[keyPrefix+"git.excludes"] = true
					}
				}
			}
			data.Git = gitVal
		} else {
			gitVal := &Git{}
			_found := false
			for _, _kv := range container.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "excludes":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						gitVal.Excludes = v
						consumed["excludes"] = true
					}
				}
			}
			if _found {
				data.Git = gitVal
			}
		}
	}
	{
		var _ftDirenv *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"direnv" {
				_ftDirenv = _ch
				break
			}
		}
		if _ftDirenv != nil {
			consumed[keyPrefix+"direnv"] = true
			direnvVal := &Direnv{}
			for _, _kv := range _ftDirenv.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "envrc":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						direnvVal.Envrc = v
						consumed[keyPrefix+"direnv.envrc"] = true
					}
				}
			}
			for _, _ch := range doc.Root().Children {
				if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"direnv.dotenv" {
					direnvVal.Dotenv = cst.ExtractStringMap(_ch)
					consumed[keyPrefix+"direnv.dotenv"] = true
					for _ik := range direnvVal.Dotenv {
						consumed[keyPrefix+"direnv.dotenv"+"."+_ik] = true
					}
					break
				}
			}
			data.Direnv = direnvVal
		} else {
			direnvVal := &Direnv{}
			_found := false
			for _, _kv := range container.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "envrc":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						direnvVal.Envrc = v
						consumed["envrc"] = true
					}
				}
			}
			for _, _ch := range doc.Root().Children {
				if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "dotenv" {
					direnvVal.Dotenv = cst.ExtractStringMap(_ch)
					_found = true
					consumed["dotenv"] = true
					for _ik := range direnvVal.Dotenv {
						consumed["dotenv"+"."+_ik] = true
					}
					break
				}
			}
			if _found {
				data.Direnv = direnvVal
			}
		}
	}
	{
		var _ftHooks *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"hooks" {
				_ftHooks = _ch
				break
			}
		}
		if _ftHooks != nil {
			consumed[keyPrefix+"hooks"] = true
			hooksVal := &Hooks{}
			for _, _kv := range _ftHooks.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "create":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.Create = &v
						consumed[keyPrefix+"hooks.create"] = true
					}
				case "stop":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.Stop = &v
						consumed[keyPrefix+"hooks.stop"] = true
					}
				case "pre-merge":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.PreMerge = &v
						consumed[keyPrefix+"hooks.pre-merge"] = true
					}
				case "on-attach":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.OnAttach = &v
						consumed[keyPrefix+"hooks.on-attach"] = true
					}
				case "on-detach":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.OnDetach = &v
						consumed[keyPrefix+"hooks.on-detach"] = true
					}
				case "disallow-main-worktree":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisallowMainWorktree = &v
						consumed[keyPrefix+"hooks.disallow-main-worktree"] = true
					}
				case "tool-use-log":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.ToolUseLog = &v
						consumed[keyPrefix+"hooks.tool-use-log"] = true
					}
				case "disable-merge":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisableMerge = &v
						consumed[keyPrefix+"hooks.disable-merge"] = true
					}
				case "disable-nix-gc":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisableNixGC = &v
						consumed[keyPrefix+"hooks.disable-nix-gc"] = true
					}
				}
			}
			data.Hooks = hooksVal
		} else {
			hooksVal := &Hooks{}
			_found := false
			for _, _kv := range container.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "create":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.Create = &v
						_found = true
						consumed["create"] = true
					}
				case "stop":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.Stop = &v
						_found = true
						consumed["stop"] = true
					}
				case "pre-merge":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.PreMerge = &v
						_found = true
						consumed["pre-merge"] = true
					}
				case "on-attach":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.OnAttach = &v
						_found = true
						consumed["on-attach"] = true
					}
				case "on-detach":
					if v, ok := cst.ExtractString(_kv); ok {
						hooksVal.OnDetach = &v
						_found = true
						consumed["on-detach"] = true
					}
				case "disallow-main-worktree":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisallowMainWorktree = &v
						_found = true
						consumed["disallow-main-worktree"] = true
					}
				case "tool-use-log":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.ToolUseLog = &v
						_found = true
						consumed["tool-use-log"] = true
					}
				case "disable-merge":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisableMerge = &v
						_found = true
						consumed["disable-merge"] = true
					}
				case "disable-nix-gc":
					if v, ok := cst.ExtractBool(_kv); ok {
						hooksVal.DisableNixGC = &v
						_found = true
						consumed["disable-nix-gc"] = true
					}
				}
			}
			if _found {
				data.Hooks = hooksVal
			}
		}
	}
	{
		var _ftSessionEntry *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"session-entry" {
				_ftSessionEntry = _ch
				break
			}
		}
		if _ftSessionEntry != nil {
			consumed[keyPrefix+"session-entry"] = true
			sessionEntryVal := &SessionEntry{}
			for _, _kv := range _ftSessionEntry.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "start":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.Start = v
						consumed[keyPrefix+"session-entry.start"] = true
					}
				case "resume":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.Resume = v
						consumed[keyPrefix+"session-entry.resume"] = true
					}
				case "liveness-probe":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.LivenessProbe = v
						consumed[keyPrefix+"session-entry.liveness-probe"] = true
					}
				case "tombstone-retention":
					if v, ok := cst.ExtractString(_kv); ok {
						sessionEntryVal.TombstoneRetention = v
						consumed[keyPrefix+"session-entry.tombstone-retention"] = true
					}
				}
			}
			for _, _ch := range doc.Root().Children {
				if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"session-entry.env" {
					sessionEntryVal.Env = cst.ExtractStringMap(_ch)
					consumed[keyPrefix+"session-entry.env"] = true
					for _ik := range sessionEntryVal.Env {
						consumed[keyPrefix+"session-entry.env"+"."+_ik] = true
					}
					break
				}
			}
			data.SessionEntry = sessionEntryVal
		} else {
			sessionEntryVal := &SessionEntry{}
			_found := false
			for _, _kv := range container.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "start":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.Start = v
						consumed["start"] = true
					}
				case "resume":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.Resume = v
						consumed["resume"] = true
					}
				case "liveness-probe":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						sessionEntryVal.LivenessProbe = v
						consumed["liveness-probe"] = true
					}
				case "tombstone-retention":
					if v, ok := cst.ExtractString(_kv); ok {
						sessionEntryVal.TombstoneRetention = v
						_found = true
						consumed["tombstone-retention"] = true
					}
				}
			}
			for _, _ch := range doc.Root().Children {
				if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "env" {
					sessionEntryVal.Env = cst.ExtractStringMap(_ch)
					_found = true
					consumed["env"] = true
					for _ik := range sessionEntryVal.Env {
						consumed["env"+"."+_ik] = true
					}
					break
				}
			}
			if _found {
				data.SessionEntry = sessionEntryVal
			}
		}
	}
	var _nodesStartCommands []*cst.Node
	_nodesStartCommands = doc.FindArrayTableNodes(keyPrefix + "start-commands")
	data.StartCommands = make([]StartCommand, len(_nodesStartCommands))
	consumed[keyPrefix+"start-commands"] = true
	for i, _node := range _nodesStartCommands {
		for _, _kv := range _node.Children {
			if _kv.Kind != cst.NodeKeyValue {
				continue
			}
			switch cst.KeyValueName(_kv) {
			case "name":
				if v, ok := cst.ExtractString(_kv); ok {
					data.StartCommands[i].Name = v
					consumed[keyPrefix+"start-commands.name"] = true
				}
			case "description":
				if v, ok := cst.ExtractString(_kv); ok {
					data.StartCommands[i].Description = v
					consumed[keyPrefix+"start-commands.description"] = true
				}
			case "arg-name":
				if v, ok := cst.ExtractString(_kv); ok {
					data.StartCommands[i].ArgName = v
					consumed[keyPrefix+"start-commands.arg-name"] = true
				}
			case "arg-help":
				if v, ok := cst.ExtractString(_kv); ok {
					data.StartCommands[i].ArgHelp = v
					consumed[keyPrefix+"start-commands.arg-help"] = true
				}
			case "arg-regex":
				if v, ok := cst.ExtractString(_kv); ok {
					data.StartCommands[i].ArgRegex = &v
					consumed[keyPrefix+"start-commands.arg-regex"] = true
				}
			case "exec-completions":
				if v, ok := cst.ExtractStringSlice(_kv); ok {
					data.StartCommands[i].ExecCompletions = v
					consumed[keyPrefix+"start-commands.exec-completions"] = true
				}
			case "exec-start":
				if v, ok := cst.ExtractStringSlice(_kv); ok {
					data.StartCommands[i].ExecStart = v
					consumed[keyPrefix+"start-commands.exec-start"] = true
				}
			}
		}
	}
	var _nodesMcps []*cst.Node
	_nodesMcps = doc.FindArrayTableNodes(keyPrefix + "mcps")
	data.MCPs = make([]MCPServerDef, len(_nodesMcps))
	consumed[keyPrefix+"mcps"] = true
	for i, _node := range _nodesMcps {
		for _, _kv := range _node.Children {
			if _kv.Kind != cst.NodeKeyValue {
				continue
			}
			switch cst.KeyValueName(_kv) {
			case "name":
				if v, ok := cst.ExtractString(_kv); ok {
					data.MCPs[i].Name = v
					consumed[keyPrefix+"mcps.name"] = true
				}
			case "command":
				if v, ok := cst.ExtractString(_kv); ok {
					data.MCPs[i].Command = v
					consumed[keyPrefix+"mcps.command"] = true
				}
			case "args":
				if v, ok := cst.ExtractStringSlice(_kv); ok {
					data.MCPs[i].Args = v
					consumed[keyPrefix+"mcps.args"] = true
				}
			}
		}
		{
			_pi := 0
			for _, _rc := range doc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_rc) == keyPrefix+"mcps" {
					if _pi > i {
						break
					}
					_pi++
					continue
				}
				if _pi == i+1 && _rc.Kind == cst.NodeTable && cst.TableHeaderKey(_rc) == keyPrefix+"mcps.env" {
					data.MCPs[i].Env = cst.ExtractStringMap(_rc)
					consumed[keyPrefix+"mcps.env"] = true
					for _ik := range data.MCPs[i].Env {
						consumed[keyPrefix+"mcps.env"+"."+_ik] = true
					}
					break
				}
			}
		}
	}
	return nil
}
func EncodeSweatfileFrom(data *Sweatfile, doc *document.Document, container *cst.Node) error {
	if data.Claude != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "claude")
		{
			if len(data.Claude.Allow) > 0 || cst.HasValue(tableNode, "allow") {
				if err := cst.SetAny(tableNode, "allow", data.Claude.Allow); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.Git != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "git")
		{
			if len(data.Git.Excludes) > 0 || cst.HasValue(tableNode, "excludes") {
				if err := cst.SetAny(tableNode, "excludes", data.Git.Excludes); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.Direnv != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "direnv")
		{
			if len(data.Direnv.Envrc) > 0 || cst.HasValue(tableNode, "envrc") {
				if err := cst.SetAny(tableNode, "envrc", data.Direnv.Envrc); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		if len(data.Direnv.Dotenv) > 0 {
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "dotenv")
			cst.DeleteAllValues(tableNode)
			for k, v := range data.Direnv.Dotenv {
				if err := cst.SetAny(tableNode, k, v); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.Hooks != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "hooks")
		if data.Hooks.Create != nil {
			if err := cst.SetAny(tableNode, "create", *data.Hooks.Create); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.Stop != nil {
			if err := cst.SetAny(tableNode, "stop", *data.Hooks.Stop); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.PreMerge != nil {
			if err := cst.SetAny(tableNode, "pre-merge", *data.Hooks.PreMerge); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.OnAttach != nil {
			if err := cst.SetAny(tableNode, "on-attach", *data.Hooks.OnAttach); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.OnDetach != nil {
			if err := cst.SetAny(tableNode, "on-detach", *data.Hooks.OnDetach); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisallowMainWorktree != nil {
			if err := cst.SetAny(tableNode, "disallow-main-worktree", *data.Hooks.DisallowMainWorktree); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.ToolUseLog != nil {
			if err := cst.SetAny(tableNode, "tool-use-log", *data.Hooks.ToolUseLog); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisableMerge != nil {
			if err := cst.SetAny(tableNode, "disable-merge", *data.Hooks.DisableMerge); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Hooks.DisableNixGC != nil {
			if err := cst.SetAny(tableNode, "disable-nix-gc", *data.Hooks.DisableNixGC); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.SessionEntry != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "session-entry")
		{
			if len(data.SessionEntry.Start) > 0 || cst.HasValue(tableNode, "start") {
				if err := cst.SetAny(tableNode, "start", data.SessionEntry.Start); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		{
			if len(data.SessionEntry.Resume) > 0 || cst.HasValue(tableNode, "resume") {
				if err := cst.SetAny(tableNode, "resume", data.SessionEntry.Resume); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		if len(data.SessionEntry.Env) > 0 {
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "env")
			cst.DeleteAllValues(tableNode)
			for k, v := range data.SessionEntry.Env {
				if err := cst.SetAny(tableNode, k, v); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		{
			if len(data.SessionEntry.LivenessProbe) > 0 || cst.HasValue(tableNode, "liveness-probe") {
				if err := cst.SetAny(tableNode, "liveness-probe", data.SessionEntry.LivenessProbe); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		if data.SessionEntry.TombstoneRetention != "" || cst.HasValue(tableNode, "tombstone-retention") {
			if err := cst.SetAny(tableNode, "tombstone-retention", data.SessionEntry.TombstoneRetention); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		_existStartCommands := cst.FindArrayTableNodes(doc.Root(), "start-commands")
		for i := range data.StartCommands {
			var container *cst.Node
			if i < len(_existStartCommands) {
				container = _existStartCommands[i]
			} else {
				container = cst.AppendArrayTableEntryAfter(doc.Root(), "start-commands")
			}
			if data.StartCommands[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.StartCommands[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.StartCommands[i].Description != "" || cst.HasValue(container, "description") {
				if err := cst.SetAny(container, "description", data.StartCommands[i].Description); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.StartCommands[i].ArgName != "" || cst.HasValue(container, "arg-name") {
				if err := cst.SetAny(container, "arg-name", data.StartCommands[i].ArgName); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.StartCommands[i].ArgHelp != "" || cst.HasValue(container, "arg-help") {
				if err := cst.SetAny(container, "arg-help", data.StartCommands[i].ArgHelp); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.StartCommands[i].ArgRegex != nil {
				if err := cst.SetAny(container, "arg-regex", *data.StartCommands[i].ArgRegex); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				if len(data.StartCommands[i].ExecCompletions) > 0 || cst.HasValue(container, "exec-completions") {
					if err := cst.SetAny(container, "exec-completions", data.StartCommands[i].ExecCompletions); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			{
				if len(data.StartCommands[i].ExecStart) > 0 || cst.HasValue(container, "exec-start") {
					if err := cst.SetAny(container, "exec-start", data.StartCommands[i].ExecStart); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
		}
	}
	{
		if len(data.AllowedMCPs) > 0 || cst.HasValue(container, "allowed-mcps") {
			if err := cst.SetAny(container, "allowed-mcps", data.AllowedMCPs); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		_existMcps := cst.FindArrayTableNodes(doc.Root(), "mcps")
		for i := range data.MCPs {
			var container *cst.Node
			if i < len(_existMcps) {
				container = _existMcps[i]
			} else {
				container = cst.AppendArrayTableEntryAfter(doc.Root(), "mcps")
			}
			if data.MCPs[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.MCPs[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.MCPs[i].Command != "" || cst.HasValue(container, "command") {
				if err := cst.SetAny(container, "command", data.MCPs[i].Command); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				if len(data.MCPs[i].Args) > 0 || cst.HasValue(container, "args") {
					if err := cst.SetAny(container, "args", data.MCPs[i].Args); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if len(data.MCPs[i].Env) > 0 {
				tableNode := cst.EnsureChildTable(doc.Root(), container, "env")
				cst.DeleteAllValues(tableNode)
				for k, v := range data.MCPs[i].Env {
					if err := cst.SetAny(tableNode, k, v); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
		}
	}
	return nil
}
