// Code generated by tommy; DO NOT EDIT.

package sweatfile

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type SweatfileDocument struct {
	data     Sweatfile
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeSweatfile(input []byte) (*SweatfileDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &SweatfileDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "claude"); tableNode != nil {
		d.consumed["claude"] = true
		claudeVal := &Claude{}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "system-prompt"); err == nil {
			claudeVal.SystemPrompt = &v
			d.consumed["claude.system-prompt"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "system-prompt-append"); err == nil {
			claudeVal.SystemPromptAppend = &v
			d.consumed["claude.system-prompt-append"] = true
		}
		if v, err := document.GetFromContainer[[]string](d.cstDoc, tableNode, "allow"); err == nil {
			claudeVal.Allow = v
			d.consumed["claude.allow"] = true
		}
		d.data.Claude = claudeVal
	} else {
		claudeVal := &Claude{}
		found := false
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "system-prompt"); err == nil {
			claudeVal.SystemPrompt = &v
			found = true
			d.consumed["system-prompt"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "system-prompt-append"); err == nil {
			claudeVal.SystemPromptAppend = &v
			found = true
			d.consumed["system-prompt-append"] = true
		}
		if found {
			d.data.Claude = claudeVal
		}
	}
	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "git"); tableNode != nil {
		d.consumed["git"] = true
		gitVal := &Git{}
		if v, err := document.GetFromContainer[[]string](d.cstDoc, tableNode, "excludes"); err == nil {
			gitVal.Excludes = v
			d.consumed["git.excludes"] = true
		}
		d.data.Git = gitVal
	} else {
		gitVal := &Git{}
		found := false
		if found {
			d.data.Git = gitVal
		}
	}
	if direnvNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "direnv"); direnvNode != nil {
		d.consumed["direnv"] = true
		direnvVal := &Direnv{}
		if v, err := document.GetFromContainer[[]string](d.cstDoc, direnvNode, "envrc"); err == nil {
			direnvVal.Envrc = v
			d.consumed["direnv.envrc"] = true
		}
		if dotenvNode := d.cstDoc.FindTableInContainer(direnvNode, "dotenv"); dotenvNode != nil {
			direnvVal.Dotenv = document.GetStringMapFromTable(dotenvNode)
			d.consumed["direnv.dotenv"] = true
			document.MarkAllConsumed(dotenvNode, "direnv.dotenv", d.consumed)
		}
		d.data.Direnv = direnvVal
	} else {
		direnvVal := &Direnv{}
		found := false
		if found {
			d.data.Direnv = direnvVal
		}
	}
	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "hooks"); tableNode != nil {
		d.consumed["hooks"] = true
		hooksVal := &Hooks{}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "create"); err == nil {
			hooksVal.Create = &v
			d.consumed["hooks.create"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "stop"); err == nil {
			hooksVal.Stop = &v
			d.consumed["hooks.stop"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "pre-merge"); err == nil {
			hooksVal.PreMerge = &v
			d.consumed["hooks.pre-merge"] = true
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "disallow-main-worktree"); err == nil {
			hooksVal.DisallowMainWorktree = &v
			d.consumed["hooks.disallow-main-worktree"] = true
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "tool-use-log"); err == nil {
			hooksVal.ToolUseLog = &v
			d.consumed["hooks.tool-use-log"] = true
		}
		d.data.Hooks = hooksVal
	} else {
		hooksVal := &Hooks{}
		found := false
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "create"); err == nil {
			hooksVal.Create = &v
			found = true
			d.consumed["create"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "stop"); err == nil {
			hooksVal.Stop = &v
			found = true
			d.consumed["stop"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "pre-merge"); err == nil {
			hooksVal.PreMerge = &v
			found = true
			d.consumed["pre-merge"] = true
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "disallow-main-worktree"); err == nil {
			hooksVal.DisallowMainWorktree = &v
			found = true
			d.consumed["disallow-main-worktree"] = true
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "tool-use-log"); err == nil {
			hooksVal.ToolUseLog = &v
			found = true
			d.consumed["tool-use-log"] = true
		}
		if found {
			d.data.Hooks = hooksVal
		}
	}
	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "session-entry"); tableNode != nil {
		d.consumed["session-entry"] = true
		sessionEntryVal := &SessionEntry{}
		if v, err := document.GetFromContainer[[]string](d.cstDoc, tableNode, "start"); err == nil {
			sessionEntryVal.Start = v
			d.consumed["session-entry.start"] = true
		}
		if v, err := document.GetFromContainer[[]string](d.cstDoc, tableNode, "resume"); err == nil {
			sessionEntryVal.Resume = v
			d.consumed["session-entry.resume"] = true
		}
		d.data.SessionEntry = sessionEntryVal
	} else {
		sessionEntryVal := &SessionEntry{}
		found := false
		if found {
			d.data.SessionEntry = sessionEntryVal
		}
	}

	return d, nil
}

func (d *SweatfileDocument) Data() *Sweatfile { return &d.data }

func (d *SweatfileDocument) Encode() ([]byte, error) {
	if d.data.Claude != nil {
		tableNode := d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "claude")
		if d.data.Claude.SystemPrompt != nil {
			if err := d.cstDoc.SetInContainer(tableNode, "system-prompt", *d.data.Claude.SystemPrompt); err != nil {
				return nil, err
			}
		}
		if d.data.Claude.SystemPromptAppend != nil {
			if err := d.cstDoc.SetInContainer(tableNode, "system-prompt-append", *d.data.Claude.SystemPromptAppend); err != nil {
				return nil, err
			}
		}
		if err := d.cstDoc.SetInContainer(tableNode, "allow", d.data.Claude.Allow); err != nil {
			return nil, err
		}
	}
	if d.data.Git != nil {
		tableNode := d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "git")
		if err := d.cstDoc.SetInContainer(tableNode, "excludes", d.data.Git.Excludes); err != nil {
			return nil, err
		}
	}
	if d.data.Direnv != nil {
		direnvNode := d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "direnv")
		if err := d.cstDoc.SetInContainer(direnvNode, "envrc", d.data.Direnv.Envrc); err != nil {
			return nil, err
		}
		if len(d.data.Direnv.Dotenv) > 0 {
			dotenvNode := d.cstDoc.EnsureTableInContainer(direnvNode, "dotenv")
			document.DeleteAllInContainer(dotenvNode)
			for k, v := range d.data.Direnv.Dotenv {
				if err := d.cstDoc.SetInContainer(dotenvNode, k, v); err != nil {
					return nil, err
				}
			}
		}
	}
	if d.data.Hooks != nil {
		tableNode := d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "hooks")
		if d.data.Hooks.Create != nil {
			if err := d.cstDoc.SetInContainer(tableNode, "create", *d.data.Hooks.Create); err != nil {
				return nil, err
			}
		}
		if d.data.Hooks.Stop != nil {
			if err := d.cstDoc.SetInContainer(tableNode, "stop", *d.data.Hooks.Stop); err != nil {
				return nil, err
			}
		}
		if d.data.Hooks.PreMerge != nil {
			if err := d.cstDoc.SetInContainer(tableNode, "pre-merge", *d.data.Hooks.PreMerge); err != nil {
				return nil, err
			}
		}
		if d.data.Hooks.DisallowMainWorktree != nil {
			if err := d.cstDoc.SetInContainer(tableNode, "disallow-main-worktree", *d.data.Hooks.DisallowMainWorktree); err != nil {
				return nil, err
			}
		}
		if d.data.Hooks.ToolUseLog != nil {
			if err := d.cstDoc.SetInContainer(tableNode, "tool-use-log", *d.data.Hooks.ToolUseLog); err != nil {
				return nil, err
			}
		}
	}
	if d.data.SessionEntry != nil {
		tableNode := d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "session-entry")
		if err := d.cstDoc.SetInContainer(tableNode, "start", d.data.SessionEntry.Start); err != nil {
			return nil, err
		}
		if err := d.cstDoc.SetInContainer(tableNode, "resume", d.data.SessionEntry.Resume); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *SweatfileDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *SweatfileDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *SweatfileDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *SweatfileDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *SweatfileDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeSweatfileInto(data *Sweatfile, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if tableNode := doc.FindTableInContainer(container, "claude"); tableNode != nil {
		consumed[keyPrefix+"claude"] = true
		claudeVal := &Claude{}
		if v, err := document.GetFromContainer[string](doc, tableNode, "system-prompt"); err == nil {
			claudeVal.SystemPrompt = &v
			consumed[keyPrefix+"claude.system-prompt"] = true
		}
		if v, err := document.GetFromContainer[string](doc, tableNode, "system-prompt-append"); err == nil {
			claudeVal.SystemPromptAppend = &v
			consumed[keyPrefix+"claude.system-prompt-append"] = true
		}
		if v, err := document.GetFromContainer[[]string](doc, tableNode, "allow"); err == nil {
			claudeVal.Allow = v
			consumed[keyPrefix+"claude.allow"] = true
		}
		data.Claude = claudeVal
	} else {
		claudeVal := &Claude{}
		found := false
		if v, err := document.GetFromContainer[string](doc, container, "system-prompt"); err == nil {
			claudeVal.SystemPrompt = &v
			found = true
			consumed[keyPrefix+"system-prompt"] = true
		}
		if v, err := document.GetFromContainer[string](doc, container, "system-prompt-append"); err == nil {
			claudeVal.SystemPromptAppend = &v
			found = true
			consumed[keyPrefix+"system-prompt-append"] = true
		}
		if found {
			data.Claude = claudeVal
		}
	}
	if tableNode := doc.FindTableInContainer(container, "git"); tableNode != nil {
		consumed[keyPrefix+"git"] = true
		gitVal := &Git{}
		if v, err := document.GetFromContainer[[]string](doc, tableNode, "excludes"); err == nil {
			gitVal.Excludes = v
			consumed[keyPrefix+"git.excludes"] = true
		}
		data.Git = gitVal
	} else {
		gitVal := &Git{}
		found := false
		if found {
			data.Git = gitVal
		}
	}
	if direnvNode := doc.FindTableInContainer(container, "direnv"); direnvNode != nil {
		consumed[keyPrefix+"direnv"] = true
		direnvVal := &Direnv{}
		if v, err := document.GetFromContainer[[]string](doc, direnvNode, "envrc"); err == nil {
			direnvVal.Envrc = v
			consumed[keyPrefix+"direnv.envrc"] = true
		}
		if dotenvNode := doc.FindTableInContainer(direnvNode, "dotenv"); dotenvNode != nil {
			direnvVal.Dotenv = document.GetStringMapFromTable(dotenvNode)
			consumed[keyPrefix+"direnv.dotenv"] = true
			document.MarkAllConsumed(dotenvNode, "direnv.dotenv", consumed)
		}
		data.Direnv = direnvVal
	} else {
		direnvVal := &Direnv{}
		found := false
		if found {
			data.Direnv = direnvVal
		}
	}
	if tableNode := doc.FindTableInContainer(container, "hooks"); tableNode != nil {
		consumed[keyPrefix+"hooks"] = true
		hooksVal := &Hooks{}
		if v, err := document.GetFromContainer[string](doc, tableNode, "create"); err == nil {
			hooksVal.Create = &v
			consumed[keyPrefix+"hooks.create"] = true
		}
		if v, err := document.GetFromContainer[string](doc, tableNode, "stop"); err == nil {
			hooksVal.Stop = &v
			consumed[keyPrefix+"hooks.stop"] = true
		}
		if v, err := document.GetFromContainer[string](doc, tableNode, "pre-merge"); err == nil {
			hooksVal.PreMerge = &v
			consumed[keyPrefix+"hooks.pre-merge"] = true
		}
		if v, err := document.GetFromContainer[bool](doc, tableNode, "disallow-main-worktree"); err == nil {
			hooksVal.DisallowMainWorktree = &v
			consumed[keyPrefix+"hooks.disallow-main-worktree"] = true
		}
		if v, err := document.GetFromContainer[bool](doc, tableNode, "tool-use-log"); err == nil {
			hooksVal.ToolUseLog = &v
			consumed[keyPrefix+"hooks.tool-use-log"] = true
		}
		data.Hooks = hooksVal
	} else {
		hooksVal := &Hooks{}
		found := false
		if v, err := document.GetFromContainer[string](doc, container, "create"); err == nil {
			hooksVal.Create = &v
			found = true
			consumed[keyPrefix+"create"] = true
		}
		if v, err := document.GetFromContainer[string](doc, container, "stop"); err == nil {
			hooksVal.Stop = &v
			found = true
			consumed[keyPrefix+"stop"] = true
		}
		if v, err := document.GetFromContainer[string](doc, container, "pre-merge"); err == nil {
			hooksVal.PreMerge = &v
			found = true
			consumed[keyPrefix+"pre-merge"] = true
		}
		if v, err := document.GetFromContainer[bool](doc, container, "disallow-main-worktree"); err == nil {
			hooksVal.DisallowMainWorktree = &v
			found = true
			consumed[keyPrefix+"disallow-main-worktree"] = true
		}
		if v, err := document.GetFromContainer[bool](doc, container, "tool-use-log"); err == nil {
			hooksVal.ToolUseLog = &v
			found = true
			consumed[keyPrefix+"tool-use-log"] = true
		}
		if found {
			data.Hooks = hooksVal
		}
	}
	if tableNode := doc.FindTableInContainer(container, "session-entry"); tableNode != nil {
		consumed[keyPrefix+"session-entry"] = true
		sessionEntryVal := &SessionEntry{}
		if v, err := document.GetFromContainer[[]string](doc, tableNode, "start"); err == nil {
			sessionEntryVal.Start = v
			consumed[keyPrefix+"session-entry.start"] = true
		}
		if v, err := document.GetFromContainer[[]string](doc, tableNode, "resume"); err == nil {
			sessionEntryVal.Resume = v
			consumed[keyPrefix+"session-entry.resume"] = true
		}
		data.SessionEntry = sessionEntryVal
	} else {
		sessionEntryVal := &SessionEntry{}
		found := false
		if found {
			data.SessionEntry = sessionEntryVal
		}
	}

	return nil
}

func EncodeSweatfileFrom(data *Sweatfile, doc *document.Document, container *cst.Node) error {
	if data.Claude != nil {
		tableNode := doc.EnsureTableInContainer(container, "claude")
		if data.Claude.SystemPrompt != nil {
			if err := doc.SetInContainer(tableNode, "system-prompt", *data.Claude.SystemPrompt); err != nil {
				return err
			}
		}
		if data.Claude.SystemPromptAppend != nil {
			if err := doc.SetInContainer(tableNode, "system-prompt-append", *data.Claude.SystemPromptAppend); err != nil {
				return err
			}
		}
		if err := doc.SetInContainer(tableNode, "allow", data.Claude.Allow); err != nil {
			return err
		}
	}
	if data.Git != nil {
		tableNode := doc.EnsureTableInContainer(container, "git")
		if err := doc.SetInContainer(tableNode, "excludes", data.Git.Excludes); err != nil {
			return err
		}
	}
	if data.Direnv != nil {
		direnvNode := doc.EnsureTableInContainer(container, "direnv")
		if err := doc.SetInContainer(direnvNode, "envrc", data.Direnv.Envrc); err != nil {
			return err
		}
		if len(data.Direnv.Dotenv) > 0 {
			dotenvNode := doc.EnsureTableInContainer(direnvNode, "dotenv")
			document.DeleteAllInContainer(dotenvNode)
			for k, v := range data.Direnv.Dotenv {
				if err := doc.SetInContainer(dotenvNode, k, v); err != nil {
					return err
				}
			}
		}
	}
	if data.Hooks != nil {
		tableNode := doc.EnsureTableInContainer(container, "hooks")
		if data.Hooks.Create != nil {
			if err := doc.SetInContainer(tableNode, "create", *data.Hooks.Create); err != nil {
				return err
			}
		}
		if data.Hooks.Stop != nil {
			if err := doc.SetInContainer(tableNode, "stop", *data.Hooks.Stop); err != nil {
				return err
			}
		}
		if data.Hooks.PreMerge != nil {
			if err := doc.SetInContainer(tableNode, "pre-merge", *data.Hooks.PreMerge); err != nil {
				return err
			}
		}
		if data.Hooks.DisallowMainWorktree != nil {
			if err := doc.SetInContainer(tableNode, "disallow-main-worktree", *data.Hooks.DisallowMainWorktree); err != nil {
				return err
			}
		}
		if data.Hooks.ToolUseLog != nil {
			if err := doc.SetInContainer(tableNode, "tool-use-log", *data.Hooks.ToolUseLog); err != nil {
				return err
			}
		}
	}
	if data.SessionEntry != nil {
		tableNode := doc.EnsureTableInContainer(container, "session-entry")
		if err := doc.SetInContainer(tableNode, "start", data.SessionEntry.Start); err != nil {
			return err
		}
		if err := doc.SetInContainer(tableNode, "resume", data.SessionEntry.Resume); err != nil {
			return err
		}
	}

	return nil
}
